import { z } from "zod";
import { performanceContextSelectionSchema } from "@/lib/validation/marketing-brain-optimization";

const optionalText = (max: number) => z.string().trim().max(max).optional().or(z.literal(""));
const stringArray = (maxItems = 30, maxLen = 100) => z.array(z.string().trim().max(maxLen)).max(maxItems).default([]);

/** Every field optional — the briefing wizard autosaves a partial patch on every change, same convention as campaignBriefingSchema/publicationPatchSchema. */
export const marketingBrainBriefingSchema = z.object({
  mode: z.enum(["quick", "advanced", "performance"]).optional(),
  /** Performance Center context selection (Fase 35) — stored alongside the rest of the briefing, purely a selection until the user explicitly starts an optimization session. */
  performanceContext: performanceContextSelectionSchema.optional(),

  description: optionalText(2000),
  productOrService: optionalText(300),
  objective: optionalText(500),
  startDate: optionalText(40),
  endDate: optionalText(40),
  platforms: stringArray(20, 40),
  brandProfileId: z.string().cuid().nullable().optional(),
  language: optionalText(10),
  timezone: optionalText(100),
  campaignMode: z.enum(["new", "existing", "duplicate"]).optional(),
  existingCampaignId: z.string().cuid().nullable().optional(),

  audience: optionalText(1000),
  audienceLocation: optionalText(300),
  audienceAgeRange: optionalText(100),
  audienceInterests: stringArray(),
  audiencePainPoints: stringArray(),
  audienceNeeds: stringArray(),
  audienceObjections: stringArray(),
  audienceAwareness: optionalText(300),
  valueProposition: optionalText(1000),
  offer: optionalText(500),
  primaryCTA: optionalText(300),
  tone: optionalText(200),
  forbiddenWords: stringArray(),
  competitors: stringArray(20, 200),
  budget: z.number().nonnegative().nullable().optional(),
  frequencyPerWeek: z.number().int().min(0).max(50).nullable().optional(),
  preferredDays: stringArray(7, 20),
  preferredHours: stringArray(24, 20),
  desiredFormats: stringArray(),
  targetMetrics: stringArray(20, 40),
  maxPieces: z.number().int().min(0).max(200).nullable().optional(),
  assigneeId: z.string().cuid().nullable().optional(),
  approverId: z.string().cuid().nullable().optional(),
  requireApproval: z.boolean().optional(),
  autoGenerateDrafts: z.boolean().optional(),
  autoAdaptPlatforms: z.boolean().optional(),
  autoCreatePublications: z.boolean().optional(),
  schedulingMode: z.enum(["manual", "automatic"]).optional(),
});
export type MarketingBrainBriefingInput = z.infer<typeof marketingBrainBriefingSchema>;

export const marketingBrainStagesConfigSchema = z.object({
  enabled: z.record(z.string(), z.boolean()),
  approvalGates: z.array(z.string()).max(12),
});

export const createMarketingBrainRunSchema = z.object({
  idempotencyKey: z.string().trim().min(10).max(100),
});

export const decideMarketingBrainApprovalSchema = z.object({
  stepKey: z.string().trim().min(1).max(60),
  decision: z.enum(["APPROVED", "REJECTED"]),
  comment: optionalText(2000),
});

/** Strict schema every AI-parsed strategy output must satisfy before being persisted — validates the pure parseCampaignStrategyText() result, per spec section 4 ("crea esquemas estrictos para todas las salidas de IA"). */
export const aiStrategyOutputSchema = z.object({
  summary: z.string().max(4000),
  audienceProfile: z.string().max(4000),
  valueProposition: z.string().max(2000),
  mainMessage: z.string().max(2000),
  objectives: z.array(z.string().max(300)).max(30),
  themes: z.array(z.string().max(300)).max(30),
  creativeAngles: z.array(z.string().max(300)).max(30),
  cta: z.string().max(300),
  risks: z.array(z.string().max(300)).max(30),
  recommendations: z.array(z.string().max(300)).max(30),
  suggestedMetrics: z.array(z.string().max(200)).max(30),
});

export const aiPillarDraftSchema = z.object({
  name: z.string().trim().min(1).max(200),
  description: z.string().max(1000),
  objective: z.string().max(500),
  percentage: z.number().int().min(0).max(100).nullable(),
  formats: z.array(z.string().max(100)).max(30),
  platforms: z.array(z.string().max(100)).max(30),
  topics: z.array(z.string().max(100)).max(30),
});
export const aiPillarsOutputSchema = z.array(aiPillarDraftSchema).min(1).max(20);

export const aiPieceDraftSchema = z.object({
  title: z.string().trim().min(1).max(300),
  idea: z.string().max(2000),
  platform: z.string().trim().min(1).max(40),
  format: z.string().max(60),
  pillarName: z.string().max(200),
  objective: z.string().max(500),
  cta: z.string().max(300),
  date: z.string().max(40),
  time: z.string().max(20),
  keywords: z.array(z.string().max(100)).max(30),
  notes: z.string().max(2000),
});
export const aiContentPlanOutputSchema = z.array(aiPieceDraftSchema).min(1).max(200);
