/**
 * The central, typed registry of internal events (spec section 8) — the
 * SINGLE place every event key, its allowed payload fields, and its
 * resource type live. Nothing else in this codebase publishes an event
 * under a free-floating string; every publisher and every condition/mapping
 * editor resolves an event definition through `findEventDefinition` below.
 */

export type AutomationEventFieldType = "string" | "number" | "boolean" | "date" | "string[]";

export interface AutomationEventFieldSpec {
  key: string;
  label: string;
  type: AutomationEventFieldType;
}

export interface AutomationEventDefinition {
  /** Stable key — never renamed once shipped; publishing code and stored WorkflowAutomationEvent.type rows both reference this. */
  key: string;
  label: string;
  description: string;
  resourceType: string;
  schemaVersion: number;
  /** Fields the payload is allowed to carry — never the resource's full row (spec sections 8/16: "no incluyas secretos ni contenido completo innecesario"). */
  fields: AutomationEventFieldSpec[];
  /** True for "X changed" events — payload additionally carries `previous`/`current`/`changedFields` (spec section 16). */
  hasTransition: boolean;
}

const STATUS_FIELDS: AutomationEventFieldSpec[] = [
  { key: "id", label: "ID", type: "string" },
  { key: "title", label: "Título", type: "string" },
  { key: "status", label: "Estado", type: "string" },
  { key: "projectId", label: "Proyecto", type: "string" },
];

export const AUTOMATION_EVENT_DEFINITIONS: AutomationEventDefinition[] = [
  {
    key: "content_item.created",
    label: "ContentItem creado",
    description: "Se creó un nuevo contenido.",
    resourceType: "CONTENT_ITEM",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "title", label: "Título", type: "string" }, { key: "type", label: "Tipo", type: "string" }, { key: "status", label: "Estado", type: "string" }, { key: "channel", label: "Canal", type: "string" }],
    hasTransition: false,
  },
  {
    key: "content_item.updated",
    label: "ContentItem actualizado",
    description: "Se actualizó un contenido existente.",
    resourceType: "CONTENT_ITEM",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "title", label: "Título", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: false,
  },
  {
    key: "content_item.status_changed",
    label: "Estado de ContentItem cambiado",
    description: "El estado editorial de un contenido cambió.",
    resourceType: "CONTENT_ITEM",
    schemaVersion: 1,
    fields: STATUS_FIELDS,
    hasTransition: true,
  },
  {
    key: "campaign.created",
    label: "Campaign creada",
    description: "Se creó una nueva campaña.",
    resourceType: "CAMPAIGN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "name", label: "Nombre", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: false,
  },
  {
    key: "campaign.updated",
    label: "Campaign actualizada",
    description: "Se actualizó una campaña existente.",
    resourceType: "CAMPAIGN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "name", label: "Nombre", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: false,
  },
  {
    key: "campaign_content_piece.created",
    label: "CampaignContentPiece creada",
    description: "Se creó una nueva pieza planificada de campaña.",
    resourceType: "CAMPAIGN_CONTENT_PIECE",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "title", label: "Título", type: "string" }, { key: "campaignId", label: "Campaña", type: "string" }, { key: "status", label: "Estado", type: "string" }, { key: "platform", label: "Plataforma", type: "string" }],
    hasTransition: false,
  },
  {
    key: "campaign_content_piece.updated",
    label: "CampaignContentPiece actualizada",
    description: "Se actualizó una pieza planificada de campaña (incluye cambios de estado).",
    resourceType: "CAMPAIGN_CONTENT_PIECE",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "title", label: "Título", type: "string" }, { key: "campaignId", label: "Campaña", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: true,
  },
  {
    key: "social_post.created",
    label: "SocialPost creado",
    description: "Se creó una nueva publicación.",
    resourceType: "SOCIAL_POST",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "platform", label: "Plataforma", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: false,
  },
  {
    key: "social_post.status_changed",
    label: "Estado de SocialPost cambiado",
    description: "El estado editorial de una publicación cambió.",
    resourceType: "SOCIAL_POST",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "platform", label: "Plataforma", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: true,
  },
  {
    key: "knowledge_source.ready",
    label: "KnowledgeSource lista",
    description: "Una fuente de Knowledge Base terminó de procesarse y quedó lista para búsqueda.",
    resourceType: "KNOWLEDGE_SOURCE",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "title", label: "Título", type: "string" }, { key: "status", label: "Estado", type: "string" }, { key: "format", label: "Formato", type: "string" }],
    hasTransition: false,
  },
  {
    key: "knowledge_source.failed",
    label: "KnowledgeSource con error",
    description: "El procesamiento de una fuente de Knowledge Base falló (incluye NEEDS_OCR).",
    resourceType: "KNOWLEDGE_SOURCE",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "title", label: "Título", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: false,
  },
  {
    key: "agent_run.completed",
    label: "AgentRun completado",
    description: "Una ejecución de AI Agent Studio terminó con éxito.",
    resourceType: "AGENT_RUN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "agentRef", label: "Agente", type: "string" }, { key: "outputType", label: "Tipo de salida", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: false,
  },
  {
    key: "agent_run.failed",
    label: "AgentRun fallido",
    description: "Una ejecución de AI Agent Studio falló.",
    resourceType: "AGENT_RUN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "agentRef", label: "Agente", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: false,
  },

  // --- Performance Strategist (Fase 36) — an AI Agent capability, never able to approve/convert/publish/schedule. ---
  {
    key: "agent_run.performance_strategist_draft_created",
    label: "Estrategia en borrador creada por Performance Strategist",
    description: "El agente Performance Strategist generó una sesión de optimización en borrador (nunca aprobada) con contexto real de Performance Center.",
    resourceType: "AGENT_RUN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID de la ejecución", type: "string" }, { key: "sessionId", label: "Sesión creada", type: "string" }, { key: "scenarioCount", label: "Escenarios generados", type: "number" }],
    hasTransition: false,
  },
  {
    key: "agent_run.performance_strategist_draft_revised",
    label: "Nueva versión de estrategia preparada por Performance Strategist",
    description: "El agente preparó una nueva versión en borrador de una sesión ya generada/aprobada, sin tocar la versión anterior.",
    resourceType: "AGENT_RUN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID de la ejecución", type: "string" }, { key: "sessionId", label: "Nueva sesión", type: "string" }, { key: "previousSessionId", label: "Sesión anterior", type: "string" }],
    hasTransition: false,
  },
  {
    key: "agent_run.performance_strategist_measurement_drafted",
    label: "Plan de medición preparado por Performance Strategist",
    description: "El agente capturó una línea base real y dejó un plan de medición en borrador para una sesión ya aprobada.",
    resourceType: "AGENT_RUN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID de la ejecución", type: "string" }, { key: "sessionId", label: "Sesión", type: "string" }, { key: "planId", label: "Plan creado", type: "string" }],
    hasTransition: false,
  },
  {
    key: "agent_run.performance_strategist_review_drafted",
    label: "Revisión posterior preparada por Performance Strategist",
    description: "El agente generó una revisión posterior determinista (nunca decide REACHED/NOT_REACHED por sí mismo) pendiente de lectura humana.",
    resourceType: "AGENT_RUN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID de la ejecución", type: "string" }, { key: "sessionId", label: "Sesión", type: "string" }, { key: "reviewId", label: "Revisión creada", type: "string" }],
    hasTransition: false,
  },
  {
    key: "agent_run.performance_strategist_insufficient_data",
    label: "Datos insuficientes detectados por Performance Strategist",
    description: "El agente determinó que los datos disponibles no eran suficientes para completar el modo solicitado con confianza.",
    resourceType: "AGENT_RUN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID de la ejecución", type: "string" }, { key: "mode", label: "Modo", type: "string" }],
    hasTransition: false,
  },
  {
    key: "marketing_brain_run.completed",
    label: "MarketingBrainRun completado",
    description: "Una ejecución de Marketing Brain terminó por completo.",
    resourceType: "MARKETING_BRAIN_RUN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "campaignId", label: "Campaña", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: false,
  },
  {
    key: "marketing_brain_run.partially_completed",
    label: "MarketingBrainRun parcialmente completado",
    description: "Una ejecución de Marketing Brain terminó de forma parcial.",
    resourceType: "MARKETING_BRAIN_RUN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "campaignId", label: "Campaña", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: false,
  },
  {
    key: "marketing_brain_run.failed",
    label: "MarketingBrainRun fallido",
    description: "Una ejecución de Marketing Brain falló.",
    resourceType: "MARKETING_BRAIN_RUN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "campaignId", label: "Campaña", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: false,
  },
  {
    key: "workflow_run.completed",
    label: "WorkflowRun completado",
    description: "Una ejecución de AI Workflows terminó con éxito.",
    resourceType: "WORKFLOW_RUN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "workflowId", label: "Workflow", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: false,
  },
  {
    key: "workflow_run.failed",
    label: "WorkflowRun fallido",
    description: "Una ejecución de AI Workflows falló.",
    resourceType: "WORKFLOW_RUN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "workflowId", label: "Workflow", type: "string" }, { key: "status", label: "Estado", type: "string" }],
    hasTransition: false,
  },

  // --- AI Performance Intelligence & Optimization Center (Fase 34) — spec section 37's exact literal event names. ---
  {
    key: "PERFORMANCE_METRIC_CREATED",
    label: "Métrica de rendimiento registrada",
    description: "Se registró una nueva métrica (manual, importada o calculada).",
    resourceType: "PERFORMANCE_METRIC_RECORD",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "metricKey", label: "Métrica", type: "string" }, { key: "resourceType", label: "Tipo de recurso", type: "string" }, { key: "source", label: "Origen", type: "string" }, { key: "value", label: "Valor", type: "number" }],
    hasTransition: false,
  },
  {
    key: "PERFORMANCE_METRIC_UPDATED",
    label: "Métrica de rendimiento actualizada",
    description: "Se corrigió o reemplazó una métrica registrada manualmente.",
    resourceType: "PERFORMANCE_METRIC_RECORD",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "metricKey", label: "Métrica", type: "string" }, { key: "value", label: "Valor", type: "number" }],
    hasTransition: false,
  },
  {
    key: "PERFORMANCE_IMPORT_COMPLETED",
    label: "Importación de métricas completada",
    description: "Una importación CSV/JSON de métricas terminó (total o parcialmente).",
    resourceType: "PERFORMANCE_IMPORT",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "kind", label: "Tipo", type: "string" }, { key: "status", label: "Estado", type: "string" }, { key: "importedRows", label: "Filas importadas", type: "number" }],
    hasTransition: false,
  },
  {
    key: "PERFORMANCE_IMPORT_FAILED",
    label: "Importación de métricas fallida",
    description: "Una importación CSV/JSON de métricas falló.",
    resourceType: "PERFORMANCE_IMPORT",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "kind", label: "Tipo", type: "string" }],
    hasTransition: false,
  },
  {
    key: "PERFORMANCE_GOAL_REACHED",
    label: "Objetivo de rendimiento alcanzado",
    description: "Un objetivo de métrica se cumplió al cierre de su periodo.",
    resourceType: "PERFORMANCE_GOAL",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "metricKey", label: "Métrica", type: "string" }, { key: "campaignId", label: "Campaña", type: "string" }],
    hasTransition: false,
  },
  {
    key: "PERFORMANCE_GOAL_MISSED",
    label: "Objetivo de rendimiento no alcanzado",
    description: "Un objetivo de métrica no se cumplió al cierre de su periodo.",
    resourceType: "PERFORMANCE_GOAL",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "metricKey", label: "Métrica", type: "string" }, { key: "campaignId", label: "Campaña", type: "string" }],
    hasTransition: false,
  },
  {
    key: "PERFORMANCE_ANOMALY_DETECTED",
    label: "Anomalía de rendimiento detectada",
    description: "Se detectó una anomalía estadística en una métrica.",
    resourceType: "PERFORMANCE_ANOMALY",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "metricKey", label: "Métrica", type: "string" }, { key: "severity", label: "Gravedad", type: "string" }, { key: "method", label: "Método", type: "string" }],
    hasTransition: false,
  },
  {
    key: "PERFORMANCE_RECOMMENDATION_CREATED",
    label: "Recomendación de rendimiento creada",
    description: "Se generó una nueva recomendación a partir de reglas deterministas.",
    resourceType: "PERFORMANCE_RECOMMENDATION",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "category", label: "Categoría", type: "string" }, { key: "priority", label: "Prioridad", type: "string" }, { key: "ruleKey", label: "Regla", type: "string" }],
    hasTransition: false,
  },
  {
    key: "PERFORMANCE_RECOMMENDATION_ACCEPTED",
    label: "Recomendación de rendimiento aceptada",
    description: "Una recomendación fue aceptada por un usuario.",
    resourceType: "PERFORMANCE_RECOMMENDATION",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "category", label: "Categoría", type: "string" }],
    hasTransition: false,
  },
  {
    key: "PERFORMANCE_EXPERIMENT_STARTED",
    label: "Experimento iniciado",
    description: "Un experimento interno pasó a estado RUNNING.",
    resourceType: "PERFORMANCE_EXPERIMENT",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "name", label: "Nombre", type: "string" }, { key: "type", label: "Tipo", type: "string" }],
    hasTransition: false,
  },
  {
    key: "PERFORMANCE_EXPERIMENT_COMPLETED",
    label: "Experimento completado",
    description: "Un experimento interno terminó con un ganador confirmado.",
    resourceType: "PERFORMANCE_EXPERIMENT",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "name", label: "Nombre", type: "string" }, { key: "winnerVariantId", label: "Variante ganadora", type: "string" }],
    hasTransition: false,
  },
  {
    key: "PERFORMANCE_EXPERIMENT_INCONCLUSIVE",
    label: "Experimento inconcluso",
    description: "Un experimento interno terminó sin un ganador estadísticamente significativo.",
    resourceType: "PERFORMANCE_EXPERIMENT",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "name", label: "Nombre", type: "string" }],
    hasTransition: false,
  },

  // --- Marketing Brain optimization loop (Fase 35) ------------------------
  {
    key: "marketing_brain_optimization.context_selected",
    label: "Contexto de rendimiento seleccionado",
    description: "Se congeló un snapshot de contexto de Performance Center para una sesión de optimización de Marketing Brain.",
    resourceType: "MARKETING_BRAIN_OPTIMIZATION_SESSION",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "contextMode", label: "Modo", type: "string" }, { key: "dataQualityLevel", label: "Calidad de datos", type: "string" }],
    hasTransition: false,
  },
  {
    key: "marketing_brain_optimization.ready_for_review",
    label: "Estrategia lista para revisión",
    description: "Se generaron escenarios estratégicos y la sesión quedó lista para decisión humana.",
    resourceType: "MARKETING_BRAIN_OPTIMIZATION_SESSION",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "scenarioCount", label: "Escenarios generados", type: "number" }],
    hasTransition: false,
  },
  {
    key: "marketing_brain_optimization.approved",
    label: "Estrategia aprobada",
    description: "Una persona aprobó explícitamente una sesión de optimización — nunca un cron, agente o automatización.",
    resourceType: "MARKETING_BRAIN_OPTIMIZATION_SESSION",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }],
    hasTransition: false,
  },
  {
    key: "marketing_brain_optimization.rejected",
    label: "Estrategia rechazada",
    description: "Una persona rechazó explícitamente una sesión de optimización.",
    resourceType: "MARKETING_BRAIN_OPTIMIZATION_SESSION",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }],
    hasTransition: false,
  },
  {
    key: "marketing_brain_optimization.archived",
    label: "Estrategia archivada",
    description: "Se archivó una sesión de optimización.",
    resourceType: "MARKETING_BRAIN_OPTIMIZATION_SESSION",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }],
    hasTransition: false,
  },
  {
    key: "marketing_brain_optimization.scenario_selected",
    label: "Escenario seleccionado",
    description: "Se eligió cuál de los escenarios generados avanza hacia aprobación.",
    resourceType: "MARKETING_BRAIN_SCENARIO",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID de la sesión", type: "string" }, { key: "kind", label: "Escenario", type: "string" }],
    hasTransition: false,
  },
  {
    key: "marketing_brain_optimization.action_converted",
    label: "Acción convertida en recurso",
    description: "Una acción propuesta de un escenario se convirtió en un recurso real en borrador.",
    resourceType: "MARKETING_BRAIN_SCENARIO_ACTION",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "actionType", label: "Tipo", type: "string" }],
    hasTransition: false,
  },
  {
    key: "marketing_brain_optimization.measurement_started",
    label: "Periodo de medición iniciado",
    description: "Se creó un plan de seguimiento posterior con una línea base real capturada.",
    resourceType: "MARKETING_BRAIN_MEASUREMENT_PLAN",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "primaryMetricKey", label: "Métrica principal", type: "string" }],
    hasTransition: false,
  },
  {
    key: "marketing_brain_optimization.review_available",
    label: "Revisión posterior disponible",
    description: "Se generó una revisión posterior comparando el valor inicial y el actual de la métrica seguida.",
    resourceType: "MARKETING_BRAIN_MEASUREMENT_REVIEW",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "goalOutcome", label: "Resultado", type: "string" }],
    hasTransition: false,
  },
  {
    key: "marketing_brain_optimization.goal_reached",
    label: "Objetivo alcanzado (revisión posterior)",
    description: "Una revisión posterior de una estrategia determinó que el objetivo seguido fue alcanzado.",
    resourceType: "MARKETING_BRAIN_MEASUREMENT_REVIEW",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }],
    hasTransition: false,
  },
  {
    key: "marketing_brain_optimization.review_indeterminate",
    label: "Resultado indeterminado por falta de datos",
    description: "Una revisión posterior no pudo determinar si el objetivo se alcanzó por falta de datos suficientes — nunca se marca como éxito ni fracaso en este caso.",
    resourceType: "MARKETING_BRAIN_MEASUREMENT_REVIEW",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }],
    hasTransition: false,
  },

  // --- AI Agent Governance & Mission Control (Fase 37) --------------------
  {
    key: "ai_agent_governance.policy_created",
    label: "Política de gobernanza creada",
    description: "Se creó una nueva versión (borrador) de la política de gobernanza de agentes de IA de un proyecto.",
    resourceType: "AI_AGENT_GOVERNANCE_POLICY",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "version", label: "Versión", type: "number" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.policy_activated",
    label: "Política de gobernanza activada",
    description: "Una versión de la política de gobernanza pasó a ser la versión activa del proyecto.",
    resourceType: "AI_AGENT_GOVERNANCE_POLICY",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "version", label: "Versión", type: "number" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.simulation_completed",
    label: "Simulación de política completada",
    description: "Un usuario autorizado simuló una decisión de gobernanza sin ejecutar nada real.",
    resourceType: "AI_AGENT_GOVERNANCE_POLICY",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "agentRef", label: "Agente", type: "string" }, { key: "decision", label: "Decisión", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.run_allowed",
    label: "Ejecución de agente permitida",
    description: "El motor de políticas permitió una ejecución de agente de IA.",
    resourceType: "AI_AGENT_GOVERNANCE_RUN",
    schemaVersion: 1,
    fields: [{ key: "runId", label: "Run", type: "string" }, { key: "agentRef", label: "Agente", type: "string" }, { key: "riskLevel", label: "Riesgo", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.run_denied",
    label: "Ejecución de agente denegada",
    description: "El motor de políticas denegó una ejecución de agente de IA.",
    resourceType: "AI_AGENT_GOVERNANCE_RUN",
    schemaVersion: 1,
    fields: [{ key: "runId", label: "Run", type: "string" }, { key: "agentRef", label: "Agente", type: "string" }, { key: "code", label: "Código", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.approval_requested",
    label: "Aprobación de ejecución solicitada",
    description: "Una ejecución de agente quedó pendiente de aprobación humana antes de poder iniciarse.",
    resourceType: "AI_AGENT_GOVERNANCE_APPROVAL",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "agentRef", label: "Agente", type: "string" }, { key: "riskLevel", label: "Riesgo", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.approval_approved",
    label: "Ejecución aprobada",
    description: "Una persona autorizada aprobó una solicitud de ejecución pendiente.",
    resourceType: "AI_AGENT_GOVERNANCE_APPROVAL",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "agentRef", label: "Agente", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.approval_rejected",
    label: "Ejecución rechazada",
    description: "Una persona autorizada rechazó una solicitud de ejecución pendiente.",
    resourceType: "AI_AGENT_GOVERNANCE_APPROVAL",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "agentRef", label: "Agente", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.budget_warning",
    label: "Presupuesto de agentes cerca del límite",
    description: "Un dimensión de presupuesto de gobernanza superó el umbral de aviso (90% consumido/reservado).",
    resourceType: "AI_AGENT_GOVERNANCE_BUDGET",
    schemaVersion: 1,
    fields: [{ key: "metric", label: "Métrica", type: "string" }, { key: "window", label: "Ventana", type: "string" }, { key: "percentage", label: "Porcentaje", type: "number" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.budget_exhausted",
    label: "Presupuesto de agentes agotado",
    description: "Una dimensión de presupuesto de gobernanza alcanzó su límite configurado.",
    resourceType: "AI_AGENT_GOVERNANCE_BUDGET",
    schemaVersion: 1,
    fields: [{ key: "metric", label: "Métrica", type: "string" }, { key: "window", label: "Ventana", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.concurrency_limit_reached",
    label: "Límite de concurrencia de agentes alcanzado",
    description: "Una ejecución fue denegada porque el proyecto o el agente ya tenían el máximo de ejecuciones activas simultáneas.",
    resourceType: "AI_AGENT_GOVERNANCE_STATE",
    schemaVersion: 1,
    fields: [{ key: "agentRef", label: "Agente", type: "string" }, { key: "observed", label: "Concurrencia observada", type: "number" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.project_paused",
    label: "Nuevas ejecuciones de agentes pausadas",
    description: "Se pausaron las nuevas ejecuciones de agentes de IA para todo el proyecto.",
    resourceType: "AI_AGENT_GOVERNANCE_STATE",
    schemaVersion: 1,
    fields: [{ key: "projectId", label: "Proyecto", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.project_resumed",
    label: "Nuevas ejecuciones de agentes reanudadas",
    description: "Se reanudaron las nuevas ejecuciones de agentes de IA del proyecto.",
    resourceType: "AI_AGENT_GOVERNANCE_STATE",
    schemaVersion: 1,
    fields: [{ key: "projectId", label: "Proyecto", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.agent_paused",
    label: "Agente pausado",
    description: "Se pausó un agente específico dentro del proyecto.",
    resourceType: "AI_AGENT_GOVERNANCE_STATE",
    schemaVersion: 1,
    fields: [{ key: "agentRef", label: "Agente", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.agent_resumed",
    label: "Agente reanudado",
    description: "Se reanudó un agente específico previamente pausado.",
    resourceType: "AI_AGENT_GOVERNANCE_STATE",
    schemaVersion: 1,
    fields: [{ key: "agentRef", label: "Agente", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.emergency_stop_enabled",
    label: "Parada de emergencia activada",
    description: "Se activó la parada de emergencia — se bloquean nuevas ejecuciones, reintentos y reanudaciones del proyecto.",
    resourceType: "AI_AGENT_GOVERNANCE_STATE",
    schemaVersion: 1,
    fields: [{ key: "projectId", label: "Proyecto", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.emergency_stop_disabled",
    label: "Parada de emergencia desactivada",
    description: "Se desactivó la parada de emergencia del proyecto.",
    resourceType: "AI_AGENT_GOVERNANCE_STATE",
    schemaVersion: 1,
    fields: [{ key: "projectId", label: "Proyecto", type: "string" }],
    hasTransition: false,
  },

  // --- AI Agent Policy Studio, Rule Matrix & Staged Rollouts (Fase 38) -----
  {
    key: "ai_agent_governance.policy_conflict_detected",
    label: "Conflicto de política detectado",
    description: "El validador determinista encontró un conflicto de tipo ERROR o WARNING en un borrador de política.",
    resourceType: "AI_AGENT_GOVERNANCE_POLICY",
    schemaVersion: 1,
    fields: [{ key: "policyId", label: "Política", type: "string" }, { key: "severity", label: "Severidad", type: "string" }, { key: "code", label: "Código", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.impact_analysis_completed",
    label: "Análisis de impacto completado",
    description: "Se calculó el impacto de activar un borrador de política sobre ejecuciones históricas reales.",
    resourceType: "AI_AGENT_GOVERNANCE_POLICY",
    schemaVersion: 1,
    fields: [{ key: "policyId", label: "Política", type: "string" }, { key: "runsAnalyzed", label: "Ejecuciones analizadas", type: "number" }, { key: "decisionChanges", label: "Cambios de decisión", type: "number" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.shadow_rollout_started",
    label: "Rollout en modo sombra iniciado",
    description: "Un borrador de política empezó a evaluarse en paralelo (SHADOW) sin afectar decisiones reales.",
    resourceType: "AI_AGENT_GOVERNANCE_POLICY",
    schemaVersion: 1,
    fields: [{ key: "policyId", label: "Política", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.limited_rollout_started",
    label: "Rollout limitado iniciado",
    description: "Un borrador de política pasó a aplicarse a un subconjunto determinista del proyecto (LIMITED).",
    resourceType: "AI_AGENT_GOVERNANCE_POLICY",
    schemaVersion: 1,
    fields: [{ key: "policyId", label: "Política", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.policy_promotion_requested",
    label: "Promoción de política solicitada",
    description: "Se solicitó aprobación humana para activar un cambio de política sensible.",
    resourceType: "AI_AGENT_GOVERNANCE_POLICY",
    schemaVersion: 1,
    fields: [{ key: "id", label: "ID", type: "string" }, { key: "policyId", label: "Política", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.policy_promoted",
    label: "Política promovida a ACTIVE",
    description: "Un borrador en rollout se activó como la política real del proyecto.",
    resourceType: "AI_AGENT_GOVERNANCE_POLICY",
    schemaVersion: 1,
    fields: [{ key: "policyId", label: "Política", type: "string" }, { key: "version", label: "Versión", type: "number" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.policy_rollback_created",
    label: "Rollback de política creado",
    description: "Se creó una nueva versión de política restaurando los valores de una versión histórica.",
    resourceType: "AI_AGENT_GOVERNANCE_POLICY",
    schemaVersion: 1,
    fields: [{ key: "policyId", label: "Política nueva", type: "string" }, { key: "sourcePolicyId", label: "Versión de origen", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.rule_expired",
    label: "Regla de política expirada",
    description: "Una regla de política alcanzó su fecha de expiración y dejó de aplicarse.",
    resourceType: "AI_AGENT_GOVERNANCE_POLICY",
    schemaVersion: 1,
    fields: [{ key: "policyId", label: "Política", type: "string" }, { key: "agentRef", label: "Agente", type: "string" }],
    hasTransition: false,
  },
  {
    key: "ai_agent_governance.unknown_agent_detected",
    label: "Agente sin cobertura detectado",
    description: "Se evaluó un agente/modo sin ninguna regla explícita en la política activa.",
    resourceType: "AI_AGENT_GOVERNANCE_POLICY",
    schemaVersion: 1,
    fields: [{ key: "agentRef", label: "Agente", type: "string" }, { key: "mode", label: "Modo", type: "string" }],
    hasTransition: false,
  },

  // --- Centro de Integraciones: Google (Fase 39) ---------------------------
  {
    key: "integration.connected",
    label: "Integración conectada",
    description: "Se completó una conexión OAuth real con un proveedor externo (p. ej. Google).",
    resourceType: "INTEGRATION",
    schemaVersion: 1,
    fields: [{ key: "provider", label: "Proveedor", type: "string" }, { key: "email", label: "Correo", type: "string" }],
    hasTransition: false,
  },
  {
    key: "integration.connection_failed",
    label: "Conexión de integración fallida",
    description: "Un intento de conexión OAuth no se completó (denegado, error de intercambio de código, etc.).",
    resourceType: "INTEGRATION",
    schemaVersion: 1,
    fields: [{ key: "provider", label: "Proveedor", type: "string" }, { key: "reason", label: "Motivo", type: "string" }],
    hasTransition: false,
  },
  {
    key: "integration.reauth_required",
    label: "Reautorización requerida",
    description: "El refresh token de una integración dejó de ser válido (invalid_grant) — se necesita reconectar.",
    resourceType: "INTEGRATION",
    schemaVersion: 1,
    fields: [{ key: "provider", label: "Proveedor", type: "string" }],
    hasTransition: false,
  },
  {
    key: "integration.disconnected",
    label: "Integración desconectada",
    description: "Se desconectó una integración externa — el historial de métricas ya importadas se conserva.",
    resourceType: "INTEGRATION",
    schemaVersion: 1,
    fields: [{ key: "provider", label: "Proveedor", type: "string" }],
    hasTransition: false,
  },
  {
    key: "integration.resource_enabled",
    label: "Propiedad de integración habilitada",
    description: "Se seleccionó/habilitó una propiedad (GA4/Search Console) para sincronización.",
    resourceType: "INTEGRATION_RESOURCE",
    schemaVersion: 1,
    fields: [{ key: "provider", label: "Proveedor", type: "string" }, { key: "resourceId", label: "Recurso", type: "string" }],
    hasTransition: false,
  },
  {
    key: "integration.resource_disabled",
    label: "Propiedad de integración deshabilitada",
    description: "Se desactivó una propiedad — deja de sincronizarse.",
    resourceType: "INTEGRATION_RESOURCE",
    schemaVersion: 1,
    fields: [{ key: "provider", label: "Proveedor", type: "string" }, { key: "resourceId", label: "Recurso", type: "string" }],
    hasTransition: false,
  },
  {
    key: "integration.sync_started",
    label: "Sincronización de integración iniciada",
    description: "Comenzó una sincronización real de métricas para una propiedad conectada.",
    resourceType: "INTEGRATION_SYNC_RUN",
    schemaVersion: 1,
    fields: [{ key: "provider", label: "Proveedor", type: "string" }, { key: "resourceId", label: "Recurso", type: "string" }],
    hasTransition: false,
  },
  {
    key: "integration.sync_completed",
    label: "Sincronización de integración completada",
    description: "Una sincronización terminó sin errores.",
    resourceType: "INTEGRATION_SYNC_RUN",
    schemaVersion: 1,
    fields: [{ key: "provider", label: "Proveedor", type: "string" }, { key: "resourceId", label: "Recurso", type: "string" }, { key: "rowsReceived", label: "Filas recibidas", type: "number" }, { key: "pointsCreated", label: "Puntos creados", type: "number" }],
    hasTransition: false,
  },
  {
    key: "integration.sync_partial",
    label: "Sincronización de integración parcial",
    description: "Una sincronización terminó, pero con datos limitados o parcialmente omitidos.",
    resourceType: "INTEGRATION_SYNC_RUN",
    schemaVersion: 1,
    fields: [{ key: "provider", label: "Proveedor", type: "string" }, { key: "resourceId", label: "Recurso", type: "string" }, { key: "rowsReceived", label: "Filas recibidas", type: "number" }, { key: "pointsCreated", label: "Puntos creados", type: "number" }],
    hasTransition: false,
  },
  {
    key: "integration.sync_failed",
    label: "Sincronización de integración fallida",
    description: "Una sincronización falló — ver el historial para el error saneado.",
    resourceType: "INTEGRATION_SYNC_RUN",
    schemaVersion: 1,
    fields: [{ key: "provider", label: "Proveedor", type: "string" }, { key: "resourceId", label: "Recurso", type: "string" }],
    hasTransition: false,
  },
  {
    key: "integration.data_stale",
    label: "Datos de integración desactualizados",
    description: "Una propiedad conectada lleva más de lo esperado sin sincronizarse.",
    resourceType: "INTEGRATION_RESOURCE",
    schemaVersion: 1,
    fields: [{ key: "provider", label: "Proveedor", type: "string" }, { key: "resourceId", label: "Recurso", type: "string" }, { key: "daysStale", label: "Días sin sincronizar", type: "number" }],
    hasTransition: false,
  },

  // --- Agente de Servicio al Cliente (Fase 40) ------------------------------
  // These events are observational only — none of them can enable the agent,
  // publish a FAQ, answer as a human, change configuration, or reveal a
  // conversation's content (spec section 32).
  {
    key: "customer_support.enabled",
    label: "Agente de soporte activado",
    description: "Un MANAGER activó el agente de servicio al cliente para este proyecto.",
    resourceType: "CUSTOMER_SUPPORT_CONFIG",
    schemaVersion: 1,
    fields: [{ key: "activatedById", label: "Activado por", type: "string" }],
    hasTransition: false,
  },
  {
    key: "customer_support.disabled",
    label: "Agente de soporte desactivado",
    description: "Se desactivó el agente de servicio al cliente para este proyecto.",
    resourceType: "CUSTOMER_SUPPORT_CONFIG",
    schemaVersion: 1,
    fields: [{ key: "deactivatedById", label: "Desactivado por", type: "string" }],
    hasTransition: false,
  },
  {
    key: "customer_support.faq_published",
    label: "FAQ publicada",
    description: "Un humano publicó una FAQ — solo entonces queda disponible para el widget público.",
    resourceType: "CUSTOMER_SUPPORT_FAQ",
    schemaVersion: 1,
    fields: [{ key: "faqId", label: "FAQ", type: "string" }],
    hasTransition: false,
  },
  {
    key: "customer_support.knowledge_approved",
    label: "Fuente de conocimiento aprobada",
    description: "Un MANAGER aprobó una fuente de conocimiento — solo entonces puede usarla el agente.",
    resourceType: "CUSTOMER_SUPPORT_KNOWLEDGE_SOURCE",
    schemaVersion: 1,
    fields: [{ key: "sourceId", label: "Fuente", type: "string" }],
    hasTransition: false,
  },
  {
    key: "customer_support.knowledge_synced",
    label: "Fuente de conocimiento sincronizada",
    description: "Se sincronizó una página interna permitida hacia una fuente de conocimiento en borrador.",
    resourceType: "CUSTOMER_SUPPORT_KNOWLEDGE_SOURCE",
    schemaVersion: 1,
    fields: [{ key: "sourceId", label: "Fuente", type: "string" }, { key: "changeDetected", label: "Cambio detectado", type: "boolean" }],
    hasTransition: false,
  },
  {
    key: "customer_support.conversation_started",
    label: "Conversación de soporte iniciada",
    description: "Un visitante inició una conversación real con el agente de soporte.",
    resourceType: "CUSTOMER_SUPPORT_CONVERSATION",
    schemaVersion: 1,
    fields: [{ key: "conversationId", label: "Conversación", type: "string" }, { key: "originPage", label: "Página de origen", type: "string" }],
    hasTransition: false,
  },
  {
    key: "customer_support.answer_generated",
    label: "Respuesta de soporte generada",
    description: "El agente respondió una pregunta (FAQ, conocimiento o IA local) — nunca incluye el texto de la respuesta.",
    resourceType: "CUSTOMER_SUPPORT_MESSAGE",
    schemaVersion: 1,
    fields: [{ key: "conversationId", label: "Conversación", type: "string" }, { key: "responseType", label: "Tipo de respuesta", type: "string" }, { key: "evidence", label: "Evidencia", type: "string" }],
    hasTransition: false,
  },
  {
    key: "customer_support.answer_not_found",
    label: "Pregunta sin respuesta",
    description: "No se encontró información aprobada suficiente para responder — se ofreció atención humana.",
    resourceType: "CUSTOMER_SUPPORT_MESSAGE",
    schemaVersion: 1,
    fields: [{ key: "conversationId", label: "Conversación", type: "string" }],
    hasTransition: false,
  },
  {
    key: "customer_support.handoff_requested",
    label: "Atención humana solicitada",
    description: "Un visitante solicitó atención humana desde el widget.",
    resourceType: "CUSTOMER_SUPPORT_HANDOFF",
    schemaVersion: 1,
    fields: [{ key: "handoffId", label: "Solicitud", type: "string" }, { key: "category", label: "Categoría", type: "string" }, { key: "priority", label: "Prioridad", type: "string" }],
    hasTransition: false,
  },
  {
    key: "customer_support.handoff_resolved",
    label: "Atención humana resuelta",
    description: "Una persona autorizada marcó una solicitud de atención humana como resuelta.",
    resourceType: "CUSTOMER_SUPPORT_HANDOFF",
    schemaVersion: 1,
    fields: [{ key: "handoffId", label: "Solicitud", type: "string" }],
    hasTransition: false,
  },
  {
    key: "customer_support.negative_feedback",
    label: "Feedback negativo de soporte",
    description: "Una respuesta del agente de soporte recibió feedback negativo.",
    resourceType: "CUSTOMER_SUPPORT_MESSAGE",
    schemaVersion: 1,
    fields: [{ key: "messageId", label: "Mensaje", type: "string" }],
    hasTransition: false,
  },
  {
    key: "customer_support.public_site_claimed",
    label: "Dominio publico asignado",
    description: "Un MANAGER asigno un dominio publico exclusivo a este proyecto para el widget de soporte.",
    resourceType: "CUSTOMER_SUPPORT_PUBLIC_SITE",
    schemaVersion: 1,
    fields: [{ key: "hostname", label: "Dominio", type: "string" }],
    hasTransition: false,
  },
];

export function findEventDefinition(key: string): AutomationEventDefinition | undefined {
  return AUTOMATION_EVENT_DEFINITIONS.find((e) => e.key === key);
}

export function listEventDefinitions(): AutomationEventDefinition[] {
  return AUTOMATION_EVENT_DEFINITIONS;
}

/** Strips a raw payload down to exactly the fields the event definition declares (plus previous/current/changedFields for transition events) — the one place "no incluyas contenido completo" is actually enforced, never trusted to each call site. */
export function sanitizeEventPayload(eventKey: string, raw: Record<string, unknown>): Record<string, unknown> {
  const def = findEventDefinition(eventKey);
  if (!def) return {};
  const clean: Record<string, unknown> = {};
  for (const field of def.fields) {
    if (field.key in raw) clean[field.key] = raw[field.key];
  }
  if (def.hasTransition) {
    if ("previous" in raw) clean.previous = raw.previous;
    if ("current" in raw) clean.current = raw.current;
    if ("changedFields" in raw) clean.changedFields = raw.changedFields;
  }
  return clean;
}
