import type { AiToolDefinition } from "@/lib/ai-center/tools/types";
import {
  buildInstagramCaptionSystemPrompt,
  buildInstagramCaptionPrompt,
  buildInstagramHashtagsSystemPrompt,
  buildInstagramHashtagsPrompt,
  buildInstagramReelIdeasSystemPrompt,
  buildInstagramReelIdeasPrompt,
  buildInstagramReelScriptSystemPrompt,
  buildInstagramReelScriptPrompt,
  buildInstagramHookSystemPrompt,
  buildInstagramHookPrompt,
  buildInstagramCarouselSystemPrompt,
  buildInstagramCarouselPrompt,
  buildInstagramStoryIdeasSystemPrompt,
  buildInstagramStoryIdeasPrompt,
  buildInstagramBioSystemPrompt,
  buildInstagramBioPrompt,
  buildInstagramCtaSystemPrompt,
  buildInstagramCtaPrompt,
  buildInstagramCalendarSystemPrompt,
  buildInstagramCalendarPrompt,
} from "@/lib/ai-center/tools/instagram-prompts";

/**
 * Every fully-implemented Instagram AI tool, as a declarative definition the
 * generic AiGenerationForm engine can render — same pattern as youtube.ts.
 * Registering these in src/lib/ai-center/tools/registry.ts is the only
 * wiring Chat IA's intent router needs to start using them automatically.
 */
export const INSTAGRAM_TOOLS: AiToolDefinition[] = [
  {
    slug: "instagram-caption",
    routeSegment: "caption",
    label: "Caption Generator",
    description: "Genera captions de Instagram con gancho en la primera línea.",
    fields: [
      { name: "tema", label: "Tema de la publicación", type: "textarea", required: true, maxLength: 500 },
      { name: "objetivo", label: "Objetivo de la publicación", type: "text", maxLength: 200 },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y profesional", maxLength: 200, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "cantidad", label: "Cantidad de opciones", type: "number", defaultValue: 3, min: 1, max: 10, required: true },
    ],
    buildSystemPrompt: buildInstagramCaptionSystemPrompt,
    buildUserPrompt: (v) =>
      buildInstagramCaptionPrompt({ tema: v.tema, objetivo: v.objetivo, tono: v.tono, idioma: v.idioma, cantidad: v.cantidad }),
    outputMode: "list",
    buildItemTitle: (v) => `Caption Instagram: ${v.tema}`,
    contentType: "SOCIAL_TEXT",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "instagram-hashtags",
    routeSegment: "hashtags",
    label: "Hashtag Generator",
    description: "Genera hashtags de Instagram combinando alcance y nicho.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "nicho", label: "Nicho de la cuenta", type: "text", maxLength: 120 },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
    ],
    buildSystemPrompt: buildInstagramHashtagsSystemPrompt,
    buildUserPrompt: (v) => buildInstagramHashtagsPrompt({ tema: v.tema, nicho: v.nicho, idioma: v.idioma }),
    outputMode: "list",
    buildItemTitle: (v) => `Hashtags Instagram: ${v.tema}`,
    contentType: "SOCIAL_TEXT",
    resultKind: "SEO_SUGGESTION",
  },
  {
    slug: "instagram-reel-ideas",
    routeSegment: "reel-ideas",
    label: "Reel Ideas",
    description: "Genera ideas de Reels organizadas por categoría.",
    fields: [
      { name: "nicho", label: "Nicho de la cuenta", type: "textarea", required: true, maxLength: 500 },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "cantidad", label: "Cantidad de ideas", type: "number", defaultValue: 8, min: 1, max: 20, required: true },
    ],
    buildSystemPrompt: buildInstagramReelIdeasSystemPrompt,
    buildUserPrompt: (v) => buildInstagramReelIdeasPrompt({ nicho: v.nicho, idioma: v.idioma, cantidad: v.cantidad }),
    outputMode: "text",
    buildItemTitle: (v) => `Ideas de Reels: ${v.nicho}`,
    contentType: "SOCIAL_TEXT",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "instagram-reel-script",
    routeSegment: "reel-script",
    label: "Reel Script",
    description: "Genera el guion completo de un Reel: hook, desarrollo, CTA y texto en pantalla.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "duracion", label: "Duración aproximada (segundos)", type: "number", defaultValue: 30, min: 5, max: 180, required: true },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y profesional", maxLength: 200, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
    ],
    buildSystemPrompt: buildInstagramReelScriptSystemPrompt,
    buildUserPrompt: (v) =>
      buildInstagramReelScriptPrompt({ tema: v.tema, duracion: v.duracion, tono: v.tono, idioma: v.idioma }),
    outputMode: "text",
    buildItemTitle: (v) => `Guion Reel: ${v.tema}`,
    contentType: "VIDEO_SCRIPT",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "instagram-hooks",
    routeSegment: "hooks",
    label: "Hook Generator",
    description: "Genera hooks que detienen el scroll para publicaciones o Reels.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y profesional", maxLength: 200, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "cantidad", label: "Cantidad de opciones", type: "number", defaultValue: 5, min: 1, max: 10, required: true },
    ],
    buildSystemPrompt: buildInstagramHookSystemPrompt,
    buildUserPrompt: (v) => buildInstagramHookPrompt({ tema: v.tema, tono: v.tono, idioma: v.idioma, cantidad: v.cantidad }),
    outputMode: "list",
    buildItemTitle: (v) => `Hooks Instagram: ${v.tema}`,
    contentType: "INTRO",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "instagram-carousel",
    routeSegment: "carousel",
    label: "Carousel Generator",
    description: "Estructura el contenido de un carrusel diapositiva por diapositiva.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "diapositivas", label: "Número de diapositivas", type: "number", defaultValue: 6, min: 3, max: 15, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
    ],
    buildSystemPrompt: buildInstagramCarouselSystemPrompt,
    buildUserPrompt: (v) => buildInstagramCarouselPrompt({ tema: v.tema, diapositivas: v.diapositivas, idioma: v.idioma }),
    outputMode: "list",
    buildItemTitle: (v) => `Carrusel Instagram: ${v.tema}`,
    contentType: "OTHER",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "instagram-story-ideas",
    routeSegment: "story-ideas",
    label: "Story Ideas",
    description: "Genera ideas de Stories con formatos interactivos.",
    fields: [
      { name: "tema", label: "Tema o nicho", type: "textarea", required: true, maxLength: 500 },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "cantidad", label: "Cantidad de ideas", type: "number", defaultValue: 8, min: 1, max: 20, required: true },
    ],
    buildSystemPrompt: buildInstagramStoryIdeasSystemPrompt,
    buildUserPrompt: (v) => buildInstagramStoryIdeasPrompt({ tema: v.tema, idioma: v.idioma, cantidad: v.cantidad }),
    outputMode: "text",
    buildItemTitle: (v) => `Ideas de Stories: ${v.tema}`,
    contentType: "SOCIAL_TEXT",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "instagram-bio",
    routeSegment: "bio",
    label: "Instagram Bio Generator",
    description: "Genera biografías de Instagram dentro del límite de 150 caracteres.",
    fields: [
      { name: "tema", label: "Tema de la cuenta", type: "textarea", required: true, maxLength: 500 },
      { name: "propuestaValor", label: "Propuesta de valor", type: "text", maxLength: 300 },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y profesional", maxLength: 200, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "cantidad", label: "Cantidad de opciones", type: "number", defaultValue: 3, min: 1, max: 10, required: true },
    ],
    buildSystemPrompt: buildInstagramBioSystemPrompt,
    buildUserPrompt: (v) =>
      buildInstagramBioPrompt({
        tema: v.tema,
        propuestaValor: v.propuestaValor,
        tono: v.tono,
        idioma: v.idioma,
        cantidad: v.cantidad,
      }),
    outputMode: "list",
    buildItemTitle: (v) => `Bio Instagram: ${v.tema}`,
    contentType: "OTHER",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "instagram-cta",
    routeSegment: "cta",
    label: "CTA Generator",
    description: "Genera llamadas a la acción para publicaciones de Instagram.",
    fields: [
      { name: "objetivo", label: "Objetivo", type: "textarea", required: true, maxLength: 300 },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y profesional", maxLength: 200, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "cantidad", label: "Cantidad de opciones", type: "number", defaultValue: 5, min: 1, max: 10, required: true },
    ],
    buildSystemPrompt: buildInstagramCtaSystemPrompt,
    buildUserPrompt: (v) => buildInstagramCtaPrompt({ objetivo: v.objetivo, tono: v.tono, idioma: v.idioma, cantidad: v.cantidad }),
    outputMode: "list",
    buildItemTitle: (v) => `CTA Instagram: ${v.objetivo}`,
    contentType: "CALL_TO_ACTION",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "instagram-calendar",
    routeSegment: "calendar",
    label: "Content Calendar",
    description: "Genera un calendario de contenido de Instagram distribuido por días.",
    fields: [
      { name: "nicho", label: "Nicho de la cuenta", type: "textarea", required: true, maxLength: 500 },
      { name: "dias", label: "Días a planificar", type: "number", defaultValue: 7, min: 1, max: 30, required: true },
      { name: "frecuencia", label: "Publicaciones por semana", type: "number", defaultValue: 3, min: 1, max: 14, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
    ],
    buildSystemPrompt: buildInstagramCalendarSystemPrompt,
    buildUserPrompt: (v) =>
      buildInstagramCalendarPrompt({ nicho: v.nicho, dias: v.dias, frecuencia: v.frecuencia, idioma: v.idioma }),
    outputMode: "list",
    buildItemTitle: (v) => `Calendario Instagram: ${v.nicho}`,
    contentType: "OTHER",
    resultKind: "CAMPAIGN_PLAN",
  },
];

export function getInstagramTool(routeSegment: string): AiToolDefinition | undefined {
  return INSTAGRAM_TOOLS.find((tool) => tool.routeSegment === routeSegment);
}
