import type { AiToolDefinition } from "@/lib/ai-center/tools/types";
import {
  buildViralVideoIdeasSystemPrompt,
  buildViralVideoIdeasPrompt,
  buildTikTokHookSystemPrompt,
  buildTikTokHookPrompt,
  buildTikTokScriptSystemPrompt,
  buildTikTokScriptPrompt,
  buildTikTokCaptionSystemPrompt,
  buildTikTokCaptionPrompt,
  buildTikTokHashtagsSystemPrompt,
  buildTikTokHashtagsPrompt,
  buildVideoSeriesPlannerSystemPrompt,
  buildVideoSeriesPlannerPrompt,
  buildTrendAdaptationSystemPrompt,
  buildTrendAdaptationPrompt,
  buildTikTokCtaSystemPrompt,
  buildTikTokCtaPrompt,
  buildTikTokBioSystemPrompt,
  buildTikTokBioPrompt,
  buildPostingStrategySystemPrompt,
  buildPostingStrategyPrompt,
} from "@/lib/ai-center/tools/tiktok-prompts";

/**
 * Every fully-implemented TikTok AI tool, as a declarative definition the
 * generic AiGenerationForm engine can render — same pattern as youtube.ts,
 * instagram.ts, social-media.ts, blog-seo.ts and email-marketing.ts.
 * Registering these in src/lib/ai-center/tools/registry.ts is the only
 * wiring Chat IA's intent router needs to start using them automatically.
 */
export const TIKTOK_AI_TOOLS: AiToolDefinition[] = [
  {
    slug: "tiktok-viral-video-ideas",
    routeSegment: "viral-ideas",
    label: "Viral Video Ideas",
    description: "Genera ideas de vídeo para TikTok organizadas por categoría, sin inventar tendencias.",
    fields: [
      { name: "nicho", label: "Nicho de la cuenta", type: "textarea", required: true, maxLength: 500 },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "cantidad", label: "Cantidad de ideas", type: "number", defaultValue: 8, min: 1, max: 20, required: true },
    ],
    buildSystemPrompt: buildViralVideoIdeasSystemPrompt,
    buildUserPrompt: (v) => buildViralVideoIdeasPrompt({ nicho: v.nicho, idioma: v.idioma, cantidad: v.cantidad }),
    outputMode: "text",
    buildItemTitle: (v) => `Ideas virales TikTok: ${v.nicho}`,
    contentType: "SOCIAL_TEXT",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "tiktok-hook-generator",
    routeSegment: "hooks",
    label: "Hook Generator",
    description: "Genera hooks que enganchan en el primer segundo y medio de un vídeo de TikTok.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y profesional", maxLength: 200, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "cantidad", label: "Cantidad de opciones", type: "number", defaultValue: 5, min: 1, max: 10, required: true },
    ],
    buildSystemPrompt: buildTikTokHookSystemPrompt,
    buildUserPrompt: (v) => buildTikTokHookPrompt({ tema: v.tema, tono: v.tono, idioma: v.idioma, cantidad: v.cantidad }),
    outputMode: "list",
    buildItemTitle: (v) => `Hooks TikTok: ${v.tema}`,
    contentType: "INTRO",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "tiktok-script-generator",
    routeSegment: "script",
    label: "TikTok Script Generator",
    description: "Genera el guion completo de un vídeo de TikTok: hook, desarrollo, CTA y texto en pantalla.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "duracion", label: "Duración aproximada (segundos)", type: "number", defaultValue: 30, min: 5, max: 180, required: true },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y profesional", maxLength: 200, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
    ],
    buildSystemPrompt: buildTikTokScriptSystemPrompt,
    buildUserPrompt: (v) =>
      buildTikTokScriptPrompt({ tema: v.tema, duracion: v.duracion, tono: v.tono, idioma: v.idioma }),
    outputMode: "text",
    buildItemTitle: (v) => `Guion TikTok: ${v.tema}`,
    contentType: "VIDEO_SCRIPT",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "tiktok-caption-generator",
    routeSegment: "caption",
    label: "Caption Generator",
    description: "Genera captions breves y casuales para TikTok.",
    fields: [
      { name: "tema", label: "Tema del vídeo", type: "textarea", required: true, maxLength: 500 },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y casual", maxLength: 200, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "cantidad", label: "Cantidad de opciones", type: "number", defaultValue: 5, min: 1, max: 10, required: true },
    ],
    buildSystemPrompt: buildTikTokCaptionSystemPrompt,
    buildUserPrompt: (v) => buildTikTokCaptionPrompt({ tema: v.tema, tono: v.tono, idioma: v.idioma, cantidad: v.cantidad }),
    outputMode: "list",
    buildItemTitle: (v) => `Caption TikTok: ${v.tema}`,
    contentType: "SOCIAL_TEXT",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "tiktok-hashtag-generator",
    routeSegment: "hashtags",
    label: "Hashtag Generator",
    description: "Genera hashtags de nicho y descubribilidad para TikTok, sin afirmar que están en tendencia.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "nicho", label: "Nicho de la cuenta", type: "text", maxLength: 120 },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
    ],
    buildSystemPrompt: buildTikTokHashtagsSystemPrompt,
    buildUserPrompt: (v) => buildTikTokHashtagsPrompt({ tema: v.tema, nicho: v.nicho, idioma: v.idioma }),
    outputMode: "list",
    buildItemTitle: (v) => `Hashtags TikTok: ${v.tema}`,
    contentType: "SOCIAL_TEXT",
    resultKind: "SEO_SUGGESTION",
  },
  {
    slug: "tiktok-video-series-planner",
    routeSegment: "series-planner",
    label: "Video Series Planner",
    description: "Planifica una serie de vídeos de TikTok conectados entre sí.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "numeroVideos", label: "Número de vídeos", type: "number", defaultValue: 5, min: 2, max: 15, required: true },
      { name: "objetivo", label: "Objetivo de la serie", type: "text", required: true, maxLength: 300 },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
    ],
    buildSystemPrompt: buildVideoSeriesPlannerSystemPrompt,
    buildUserPrompt: (v) =>
      buildVideoSeriesPlannerPrompt({ tema: v.tema, numeroVideos: v.numeroVideos, objetivo: v.objetivo, idioma: v.idioma }),
    outputMode: "list",
    buildItemTitle: (v) => `Serie de vídeos: ${v.tema}`,
    contentType: "OTHER",
    resultKind: "CAMPAIGN_PLAN",
  },
  {
    slug: "tiktok-trend-adaptation",
    routeSegment: "trend-adaptation",
    label: "Trend Adaptation Assistant",
    description: "Adapta una tendencia que tú describas a tu nicho — nunca asume que una tendencia sigue vigente.",
    fields: [
      { name: "tendencia", label: "Describe la tendencia, formato o sonido", type: "textarea", required: true, maxLength: 1000 },
      { name: "nicho", label: "Nicho de la cuenta", type: "text", required: true, maxLength: 200 },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
    ],
    buildSystemPrompt: buildTrendAdaptationSystemPrompt,
    buildUserPrompt: (v) => buildTrendAdaptationPrompt({ tendencia: v.tendencia, nicho: v.nicho, idioma: v.idioma }),
    outputMode: "text",
    buildItemTitle: () => "Adaptación de tendencia",
    contentType: "OTHER",
    resultKind: "ADAPTATION",
  },
  {
    slug: "tiktok-cta-generator",
    routeSegment: "cta",
    label: "Call To Action Generator",
    description: "Genera llamadas a la acción breves y naturales para TikTok.",
    fields: [
      { name: "objetivo", label: "Objetivo", type: "text", required: true, maxLength: 300 },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y casual", maxLength: 200, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "cantidad", label: "Cantidad de opciones", type: "number", defaultValue: 5, min: 1, max: 10, required: true },
    ],
    buildSystemPrompt: buildTikTokCtaSystemPrompt,
    buildUserPrompt: (v) => buildTikTokCtaPrompt({ objetivo: v.objetivo, tono: v.tono, idioma: v.idioma, cantidad: v.cantidad }),
    outputMode: "list",
    buildItemTitle: (v) => `CTA TikTok: ${v.objetivo}`,
    contentType: "CALL_TO_ACTION",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "tiktok-profile-bio",
    routeSegment: "bio",
    label: "Profile Bio Generator",
    description: "Genera biografías de TikTok dentro del límite de 80 caracteres.",
    fields: [
      { name: "tema", label: "Tema de la cuenta", type: "textarea", required: true, maxLength: 500 },
      { name: "propuestaValor", label: "Propuesta de valor", type: "text", maxLength: 300 },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y casual", maxLength: 200, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "cantidad", label: "Cantidad de opciones", type: "number", defaultValue: 3, min: 1, max: 10, required: true },
    ],
    buildSystemPrompt: buildTikTokBioSystemPrompt,
    buildUserPrompt: (v) =>
      buildTikTokBioPrompt({
        tema: v.tema,
        propuestaValor: v.propuestaValor,
        tono: v.tono,
        idioma: v.idioma,
        cantidad: v.cantidad,
      }),
    outputMode: "list",
    buildItemTitle: (v) => `Bio TikTok: ${v.tema}`,
    contentType: "OTHER",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "tiktok-posting-strategy",
    routeSegment: "posting-strategy",
    label: "Posting Strategy Generator",
    description: "Sugiere una estrategia de publicación orientativa para TikTok, sin datos de analítica real.",
    fields: [
      { name: "nicho", label: "Nicho de la cuenta", type: "textarea", required: true, maxLength: 500 },
      { name: "objetivo", label: "Objetivo", type: "text", required: true, maxLength: 300 },
      { name: "frecuencia", label: "Vídeos por semana", type: "number", defaultValue: 5, min: 1, max: 21, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
    ],
    buildSystemPrompt: buildPostingStrategySystemPrompt,
    buildUserPrompt: (v) =>
      buildPostingStrategyPrompt({ nicho: v.nicho, objetivo: v.objetivo, frecuencia: v.frecuencia, idioma: v.idioma }),
    outputMode: "text",
    buildItemTitle: (v) => `Estrategia TikTok: ${v.nicho}`,
    contentType: "OTHER",
    resultKind: "CAMPAIGN_PLAN",
  },
];

export function getTikTokTool(routeSegment: string): AiToolDefinition | undefined {
  return TIKTOK_AI_TOOLS.find((tool) => tool.routeSegment === routeSegment);
}
