import type { AiToolDefinition } from "@/lib/ai-center/tools/types";
import {
  buildYoutubeTitlesSystemPrompt,
  buildYoutubeTitlesPrompt,
  buildYoutubeDescriptionSystemPrompt,
  buildYoutubeDescriptionPrompt,
  buildYoutubeHashtagsSystemPrompt,
  buildYoutubeHashtagsPrompt,
  buildYoutubeTagsSystemPrompt,
  buildYoutubeTagsPrompt,
  buildYoutubeHooksSystemPrompt,
  buildYoutubeHooksPrompt,
  buildYoutubeChaptersSystemPrompt,
  buildYoutubeChaptersPrompt,
  buildYoutubeIdeasSystemPrompt,
  buildYoutubeIdeasPrompt,
  buildYoutubeScriptSystemPrompt,
  buildYoutubeScriptPrompt,
} from "@/lib/ai-center/tools/youtube-prompts";

/**
 * Every fully-implemented YouTube AI tool, as a declarative definition the
 * generic AiGenerationForm engine can render. Adding Instagram/TikTok/etc.
 * later means adding a sibling file like this one — nothing here or in the
 * generic form needs to change.
 */
export const YOUTUBE_TOOLS: AiToolDefinition[] = [
  {
    slug: "youtube-titulos",
    routeSegment: "titulos",
    label: "Generador de títulos",
    description: "Genera varios títulos de vídeo con gancho a partir de un tema.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "nicho", label: "Nicho del canal", type: "text", maxLength: 120 },
      { name: "audiencia", label: "Audiencia", type: "text", maxLength: 200 },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y profesional", maxLength: 200, required: true },
      { name: "cantidad", label: "Cantidad de títulos", type: "number", defaultValue: 5, min: 1, max: 10, required: true },
    ],
    buildSystemPrompt: buildYoutubeTitlesSystemPrompt,
    buildUserPrompt: (v) =>
      buildYoutubeTitlesPrompt({
        tema: v.tema,
        nicho: v.nicho,
        audiencia: v.audiencia,
        idioma: v.idioma,
        tono: v.tono,
        cantidad: v.cantidad,
      }),
    outputMode: "list",
    buildItemTitle: (v) => `Títulos YouTube: ${v.tema}`,
    contentType: "TITLE",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "youtube-descripciones",
    routeSegment: "descripcion",
    label: "Generador de descripción",
    description: "Redacta una descripción optimizada para YouTube.",
    fields: [
      { name: "tema", label: "Tema del vídeo", type: "text", required: true, maxLength: 300 },
      { name: "resumen", label: "Resumen del contenido", type: "textarea", required: true, maxLength: 2000 },
      { name: "palabrasClave", label: "Palabras clave", type: "text", maxLength: 300 },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y profesional", maxLength: 200, required: true },
    ],
    buildSystemPrompt: buildYoutubeDescriptionSystemPrompt,
    buildUserPrompt: (v) =>
      buildYoutubeDescriptionPrompt({
        tema: v.tema,
        resumen: v.resumen,
        palabrasClave: v.palabrasClave,
        idioma: v.idioma,
        tono: v.tono,
      }),
    outputMode: "text",
    buildItemTitle: (v) => `Descripción YouTube: ${v.tema}`,
    contentType: "OTHER",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "youtube-hashtags",
    routeSegment: "hashtags",
    label: "Generador de hashtags",
    description: "Genera hashtags relevantes para el vídeo.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "nicho", label: "Nicho del canal", type: "text", maxLength: 120 },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
    ],
    buildSystemPrompt: buildYoutubeHashtagsSystemPrompt,
    buildUserPrompt: (v) => buildYoutubeHashtagsPrompt({ tema: v.tema, nicho: v.nicho, idioma: v.idioma }),
    outputMode: "list",
    buildItemTitle: (v) => `Hashtags YouTube: ${v.tema}`,
    contentType: "SOCIAL_TEXT",
    resultKind: "SEO_SUGGESTION",
  },
  {
    slug: "youtube-etiquetas",
    routeSegment: "etiquetas",
    label: "Generador de etiquetas",
    description: "Genera etiquetas SEO para el buscador de YouTube, sin duplicados.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "nicho", label: "Nicho del canal", type: "text", maxLength: 120 },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
    ],
    buildSystemPrompt: buildYoutubeTagsSystemPrompt,
    buildUserPrompt: (v) => buildYoutubeTagsPrompt({ tema: v.tema, nicho: v.nicho, idioma: v.idioma }),
    outputMode: "list",
    buildItemTitle: (v) => `Etiquetas YouTube: ${v.tema}`,
    contentType: "OTHER",
    resultKind: "SEO_SUGGESTION",
  },
  {
    slug: "youtube-hooks",
    routeSegment: "hooks",
    label: "Generador de hooks",
    description: "Genera varias opciones para los primeros segundos del vídeo.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y profesional", maxLength: 200, required: true },
      { name: "cantidad", label: "Cantidad de opciones", type: "number", defaultValue: 5, min: 1, max: 10, required: true },
    ],
    buildSystemPrompt: buildYoutubeHooksSystemPrompt,
    buildUserPrompt: (v) => buildYoutubeHooksPrompt({ tema: v.tema, tono: v.tono, idioma: v.idioma, cantidad: v.cantidad }),
    outputMode: "list",
    buildItemTitle: (v) => `Hooks YouTube: ${v.tema}`,
    contentType: "INTRO",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "youtube-capitulos",
    routeSegment: "capitulos",
    label: "Generador de capítulos",
    description: "Genera la línea de tiempo completa de capítulos del vídeo.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "estructura", label: "Estructura o secciones", type: "textarea", required: true, maxLength: 1000 },
      { name: "duracion", label: "Duración aproximada (minutos)", type: "number", defaultValue: 10, min: 1, max: 240, required: true },
    ],
    buildSystemPrompt: buildYoutubeChaptersSystemPrompt,
    buildUserPrompt: (v) => buildYoutubeChaptersPrompt({ tema: v.tema, estructura: v.estructura, duracion: v.duracion }),
    outputMode: "list",
    buildItemTitle: (v) => `Capítulos YouTube: ${v.tema}`,
    contentType: "OTHER",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "youtube-ideas",
    routeSegment: "ideas",
    label: "Ideas de videos",
    description: "Genera ideas de vídeo organizadas por categoría.",
    fields: [
      { name: "nicho", label: "Nicho del canal", type: "textarea", required: true, maxLength: 500 },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
      { name: "cantidad", label: "Cantidad de ideas", type: "number", defaultValue: 8, min: 1, max: 20, required: true },
    ],
    buildSystemPrompt: buildYoutubeIdeasSystemPrompt,
    buildUserPrompt: (v) => buildYoutubeIdeasPrompt({ nicho: v.nicho, idioma: v.idioma, cantidad: v.cantidad }),
    outputMode: "text",
    buildItemTitle: (v) => `Ideas de vídeo: ${v.nicho}`,
    contentType: "SOCIAL_TEXT",
    resultKind: "CONTENT_GENERATION",
  },
  {
    slug: "youtube-guiones",
    routeSegment: "guion",
    label: "Guion IA",
    description: "Genera el guion completo del vídeo con introducción, desarrollo, llamado a la acción y conclusión.",
    fields: [
      { name: "tema", label: "Tema", type: "textarea", required: true, maxLength: 500 },
      { name: "duracion", label: "Duración aproximada (minutos)", type: "number", defaultValue: 10, min: 1, max: 240, required: true },
      { name: "tono", label: "Tono", type: "text", defaultValue: "Cercano y profesional", maxLength: 200, required: true },
      { name: "idioma", label: "Idioma", type: "text", defaultValue: "es", maxLength: 10, required: true },
    ],
    buildSystemPrompt: buildYoutubeScriptSystemPrompt,
    buildUserPrompt: (v) => buildYoutubeScriptPrompt({ tema: v.tema, duracion: v.duracion, tono: v.tono, idioma: v.idioma }),
    outputMode: "text",
    buildItemTitle: (v) => `Guion YouTube: ${v.tema}`,
    contentType: "VIDEO_SCRIPT",
    resultKind: "CONTENT_GENERATION",
  },
];

export function getYoutubeTool(routeSegment: string): AiToolDefinition | undefined {
  return YOUTUBE_TOOLS.find((tool) => tool.routeSegment === routeSegment);
}
