import {
  Bot,
  FileText,
  Search,
  Share2,
  MonitorPlay,
  Music2,
  Camera,
  ThumbsUp,
  Megaphone,
  Workflow,
  Code2,
  Files,
  Wand2,
  Image,
  Clapperboard,
  AudioLines,
  Briefcase,
  Zap,
  TrendingUp,
  Newspaper,
  Mail,
  Flame,
  Users2,
  IdCard,
  Aperture,
  ScrollText,
  Film,
} from "lucide-react";
import type { AiToolCategory } from "@/lib/ai-center/types";

/**
 * Single source of truth for the AI Center: every category and every tool
 * (built or not) is one entry here. Adding a future tool never touches the
 * Sidebar, a layout, or the data model — just this array. "coming-soon"
 * tools have no `href` and render as a disabled card until a real page for
 * them ships in a later phase.
 */
export const AI_CENTER_CATEGORIES: AiToolCategory[] = [
  {
    slug: "asistente-ia",
    label: "Asistente IA",
    description: "Chat con memoria de conversación y contexto de tu proyecto.",
    icon: Bot,
    tools: [
      {
        slug: "asistente-chat",
        label: "Asistente de chat",
        description: "Conversa con la IA local del proyecto; guarda historial de conversaciones.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/assistant`,
      },
    ],
  },
  {
    slug: "contenido",
    label: "Contenido",
    description: "Redacción y edición de textos largos.",
    icon: FileText,
    tools: [
      {
        slug: "generador-contenido",
        label: "Generador de contenido",
        description: "Crea un primer borrador de artículo o publicación desde un tema.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/content/new`,
      },
      {
        slug: "adaptador-contenido",
        label: "Adaptador de contenido",
        description: "Adapta una pieza existente al formato de otra plataforma.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/content/adapt`,
      },
      { slug: "reescritor", label: "Reescritor", description: "Reescribe un texto conservando su significado.", status: "coming-soon" },
      { slug: "humanizador", label: "Humanizador", description: "Suaviza texto generado por IA para sonar más natural.", status: "coming-soon" },
      { slug: "resumidor", label: "Resumidor", description: "Resume un texto largo en puntos clave.", status: "coming-soon" },
      { slug: "corrector", label: "Corrector", description: "Corrige ortografía, gramática y estilo.", status: "coming-soon" },
      { slug: "traductor", label: "Traductor", description: "Traduce contenido entre idiomas.", status: "coming-soon" },
      { slug: "expandir-texto", label: "Expandir texto", description: "Alarga un texto breve con más detalle.", status: "coming-soon" },
      { slug: "acortar-texto", label: "Acortar texto", description: "Reduce un texto a su versión más breve.", status: "coming-soon" },
    ],
  },
  {
    slug: "seo",
    label: "SEO",
    description: "Optimización para motores de búsqueda.",
    icon: Search,
    tools: [
      {
        slug: "herramientas-seo",
        label: "Herramientas SEO",
        description: "Analiza y mejora el SEO de una pieza de contenido.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/seo`,
      },
      { slug: "palabra-clave", label: "Palabra clave principal", description: "Sugiere la palabra clave principal para un tema.", status: "coming-soon" },
      { slug: "keywords-secundarias", label: "Keywords secundarias", description: "Genera palabras clave secundarias relacionadas.", status: "coming-soon" },
      { slug: "cluster-contenido", label: "Cluster de contenido", description: "Agrupa temas relacionados en un cluster SEO.", status: "coming-soon" },
      { slug: "meta-descripcion", label: "Meta descripción", description: "Redacta una meta descripción optimizada.", status: "coming-soon" },
      { slug: "faq-seo", label: "FAQ", description: "Genera preguntas frecuentes para una página.", status: "coming-soon" },
      { slug: "schema-seo", label: "Schema", description: "Sugiere marcado estructurado (schema.org).", status: "coming-soon" },
      { slug: "snippet-seo", label: "Snippet destacado", description: "Redacta contenido orientado a snippet destacado.", status: "coming-soon" },
      { slug: "enlaces-internos", label: "Enlaces internos", description: "Sugiere enlaces internos relevantes.", status: "coming-soon" },
      { slug: "enlaces-externos", label: "Enlaces externos", description: "Sugiere fuentes externas de referencia.", status: "coming-soon" },
    ],
  },
  {
    slug: "redes-sociales",
    label: "Redes sociales",
    description: "Herramientas transversales para publicaciones sociales.",
    icon: Share2,
    tools: [
      {
        slug: "ideas-redes-sociales",
        label: "Ideas para redes sociales",
        description: "Genera ideas de publicaciones para una plataforma y tema.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/social/ideas`,
      },
      {
        slug: "analizador-publicaciones",
        label: "Analizador de publicaciones",
        description: "Comprueba longitud, gancho, hashtags, CTA y repetición.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/social/analyzer`,
      },
      {
        slug: "generador-respuestas",
        label: "Generador de respuestas",
        description: "Redacta una respuesta a un comentario o mensaje.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/replies`,
      },
    ],
  },
  {
    slug: "youtube",
    label: "YouTube",
    description: "Herramientas específicas para vídeo largo en YouTube.",
    icon: MonitorPlay,
    tools: [
      {
        slug: "youtube-titulos",
        label: "Generador de títulos",
        description: "Genera varios títulos de vídeo con gancho a partir de un tema.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/youtube/titulos`,
      },
      {
        slug: "youtube-descripciones",
        label: "Generador de descripción",
        description: "Redacta una descripción optimizada para YouTube.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/youtube/descripcion`,
      },
      {
        slug: "youtube-hashtags",
        label: "Generador de hashtags",
        description: "Genera hashtags relevantes para el vídeo.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/youtube/hashtags`,
      },
      {
        slug: "youtube-etiquetas",
        label: "Generador de etiquetas",
        description: "Genera etiquetas SEO para el vídeo, sin duplicados.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/youtube/etiquetas`,
      },
      {
        slug: "youtube-hooks",
        label: "Generador de hooks",
        description: "Genera varias opciones para los primeros segundos del vídeo.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/youtube/hooks`,
      },
      {
        slug: "youtube-capitulos",
        label: "Generador de capítulos",
        description: "Genera la línea de tiempo completa de capítulos del vídeo.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/youtube/capitulos`,
      },
      {
        slug: "youtube-ideas",
        label: "Ideas de videos",
        description: "Genera ideas de vídeo organizadas por categoría.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/youtube/ideas`,
      },
      {
        slug: "youtube-guiones",
        label: "Guion IA",
        description: "Genera el guion completo del vídeo: introducción, desarrollo, llamado a la acción y conclusión.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/youtube/guion`,
      },
      { slug: "youtube-thumbnail-prompts", label: "Thumbnail prompts", description: "Genera prompts para miniaturas.", status: "coming-soon" },
    ],
  },
  {
    slug: "tiktok",
    label: "TikTok",
    description: "Herramientas para vídeo corto en TikTok.",
    icon: Music2,
    tools: [
      { slug: "tiktok-ideas", label: "Ideas", description: "Genera ideas de vídeo corto.", status: "coming-soon" },
      { slug: "tiktok-guiones", label: "Guiones", description: "Escribe el guion de un vídeo corto.", status: "coming-soon" },
      { slug: "tiktok-hooks", label: "Hooks", description: "Redacta el gancho inicial del vídeo.", status: "coming-soon" },
      { slug: "tiktok-descripciones", label: "Descripciones", description: "Redacta la descripción del vídeo.", status: "coming-soon" },
      { slug: "tiktok-hashtags", label: "Hashtags", description: "Sugiere hashtags relevantes.", status: "coming-soon" },
    ],
  },
  {
    slug: "instagram",
    label: "Instagram",
    description: "Herramientas para publicaciones en Instagram.",
    icon: Camera,
    tools: [
      {
        slug: "instagram-caption",
        label: "Caption Generator",
        description: "Genera captions de Instagram con gancho en la primera línea.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/instagram/caption`,
      },
      {
        slug: "instagram-hashtags",
        label: "Hashtag Generator",
        description: "Genera hashtags de Instagram combinando alcance y nicho.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/instagram/hashtags`,
      },
      {
        slug: "instagram-reel-ideas",
        label: "Reel Ideas",
        description: "Genera ideas de Reels organizadas por categoría.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/instagram/reel-ideas`,
      },
      {
        slug: "instagram-reel-script",
        label: "Reel Script",
        description: "Genera el guion completo de un Reel: hook, desarrollo, CTA y texto en pantalla.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/instagram/reel-script`,
      },
      {
        slug: "instagram-hooks",
        label: "Hook Generator",
        description: "Genera hooks que detienen el scroll para publicaciones o Reels.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/instagram/hooks`,
      },
      {
        slug: "instagram-carousel",
        label: "Carousel Generator",
        description: "Estructura el contenido de un carrusel diapositiva por diapositiva.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/instagram/carousel`,
      },
      {
        slug: "instagram-story-ideas",
        label: "Story Ideas",
        description: "Genera ideas de Stories con formatos interactivos.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/instagram/story-ideas`,
      },
      {
        slug: "instagram-bio",
        label: "Instagram Bio Generator",
        description: "Genera biografías de Instagram dentro del límite de 150 caracteres.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/instagram/bio`,
      },
      {
        slug: "instagram-cta",
        label: "CTA Generator",
        description: "Genera llamadas a la acción para publicaciones de Instagram.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/instagram/cta`,
      },
      {
        slug: "instagram-calendar",
        label: "Content Calendar",
        description: "Genera un calendario de contenido de Instagram distribuido por días.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/instagram/calendar`,
      },
    ],
  },
  {
    slug: "facebook",
    label: "Facebook",
    description: "Herramientas para publicaciones en Facebook.",
    icon: ThumbsUp,
    tools: [
      { slug: "facebook-posts", label: "Posts", description: "Redacta una publicación de Facebook.", status: "coming-soon" },
      { slug: "facebook-encuestas", label: "Encuestas", description: "Genera una encuesta para la comunidad.", status: "coming-soon" },
      { slug: "facebook-preguntas", label: "Preguntas", description: "Genera preguntas para fomentar comentarios.", status: "coming-soon" },
      { slug: "facebook-descripciones", label: "Descripciones", description: "Redacta descripciones de página o evento.", status: "coming-soon" },
    ],
  },
  {
    slug: "marketing",
    label: "Marketing",
    description: "Email marketing y páginas de conversión.",
    icon: Megaphone,
    tools: [
      { slug: "marketing-email", label: "Email", description: "Redacta un email de marketing.", status: "coming-soon" },
      { slug: "marketing-newsletter", label: "Newsletter", description: "Redacta una newsletter periódica.", status: "coming-soon" },
      { slug: "marketing-landing", label: "Landing", description: "Redacta el copy de una landing page.", status: "coming-soon" },
      { slug: "marketing-cta", label: "CTA", description: "Genera llamadas a la acción.", status: "coming-soon" },
      { slug: "marketing-ofertas", label: "Ofertas", description: "Redacta una oferta o promoción.", status: "coming-soon" },
    ],
  },
  {
    slug: "automatizacion",
    label: "Automatización",
    description: "Generación de contenido para flujos automatizados.",
    icon: Workflow,
    tools: [],
  },
  {
    slug: "programacion",
    label: "Programación",
    description: "Ayuda con código.",
    icon: Code2,
    tools: [
      { slug: "codigo-explicador", label: "Explicador", description: "Explica qué hace un fragmento de código.", status: "coming-soon" },
      { slug: "codigo-sql", label: "SQL", description: "Genera o explica una consulta SQL.", status: "coming-soon" },
      { slug: "codigo-regex", label: "Regex", description: "Genera o explica una expresión regular.", status: "coming-soon" },
      { slug: "codigo-api", label: "API", description: "Genera documentación de un endpoint.", status: "coming-soon" },
      { slug: "codigo-debug", label: "Debug", description: "Ayuda a depurar un error de código.", status: "coming-soon" },
    ],
  },
  {
    slug: "documentos",
    label: "Documentos",
    description: "Generación de documentos largos.",
    icon: Files,
    tools: [],
  },
  {
    slug: "prompts",
    label: "Prompts",
    description: "Prompts optimizados para generadores de imagen y vídeo externos.",
    icon: Wand2,
    tools: [
      { slug: "prompts-midjourney", label: "Midjourney", description: "Genera un prompt optimizado para Midjourney.", status: "coming-soon" },
      { slug: "prompts-flux", label: "Flux", description: "Genera un prompt optimizado para Flux.", status: "coming-soon" },
      { slug: "prompts-imagen", label: "Imagen", description: "Genera un prompt optimizado para Google Imagen.", status: "coming-soon" },
      { slug: "prompts-runway", label: "Runway", description: "Genera un prompt optimizado para Runway.", status: "coming-soon" },
      { slug: "prompts-veo", label: "Veo", description: "Genera un prompt optimizado para Google Veo.", status: "coming-soon" },
      { slug: "prompts-kling", label: "Kling", description: "Genera un prompt optimizado para Kling.", status: "coming-soon" },
    ],
  },
  {
    slug: "imagenes",
    label: "Imágenes",
    description: "Generación y edición de imágenes.",
    icon: Image,
    tools: [],
  },
  {
    slug: "video",
    label: "Video",
    description: "Generación y edición de vídeo.",
    icon: Clapperboard,
    tools: [],
  },
  {
    slug: "audio",
    label: "Audio",
    description: "Generación y edición de audio.",
    icon: AudioLines,
    tools: [],
  },
  {
    slug: "negocio",
    label: "Negocio",
    description: "Estrategia y planificación de negocio.",
    icon: Briefcase,
    tools: [
      { slug: "plan-negocio", label: "Plan de negocio", description: "Esboza un plan de negocio.", status: "coming-soon" },
      { slug: "buyer-persona", label: "Buyer persona", description: "Define el perfil de tu cliente ideal.", status: "coming-soon" },
      { slug: "embudos", label: "Embudos", description: "Diseña un embudo de conversión.", status: "coming-soon" },
      { slug: "estrategias", label: "Estrategias", description: "Genera una estrategia de contenido.", status: "coming-soon" },
    ],
  },
  {
    slug: "productividad",
    label: "Productividad",
    description: "Organización del trabajo diario.",
    icon: Zap,
    tools: [],
  },
  {
    slug: "social-media-ai",
    label: "Social Media AI",
    description: "Estrategia y planificación multiplataforma: Instagram, Facebook, TikTok, YouTube, LinkedIn, X, Pinterest y Threads.",
    icon: TrendingUp,
    tools: [
      {
        slug: "social-calendar",
        label: "Content Calendar",
        description: "Genera un calendario de contenido distribuido por días para varias plataformas.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/social-media/calendar`,
      },
      {
        slug: "social-monthly-planner",
        label: "Monthly Content Planner",
        description: "Genera un plan de contenido organizado por semanas para todo un mes.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/social-media/monthly-planner`,
      },
      {
        slug: "social-multi-platform-post",
        label: "Multi Platform Post Generator",
        description: "Genera una versión nativa de una publicación para cada plataforma indicada.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/social-media/multi-platform-post`,
      },
      {
        slug: "social-repurpose",
        label: "Repurpose Content",
        description: "Reaprovecha una pieza de contenido existente en versiones nativas para otras plataformas.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/social-media/repurpose`,
      },
      {
        slug: "social-viral-ideas",
        label: "Viral Content Ideas",
        description: "Genera ideas de contenido con potencial de interacción, organizadas por categoría.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/social-media/viral-ideas`,
      },
      {
        slug: "social-audience-analyzer",
        label: "Audience Analyzer",
        description: "Analiza tu audiencia y sugiere perfiles, intereses y puntos de dolor.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/social-media/audience-analyzer`,
      },
      {
        slug: "social-growth-strategy",
        label: "Growth Strategy Generator",
        description: "Genera una estrategia de crecimiento accionable para tus redes sociales.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/social-media/growth-strategy`,
      },
      {
        slug: "social-engagement-booster",
        label: "Engagement Booster",
        description: "Sugiere mejoras concretas para aumentar la interacción de una publicación.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/social-media/engagement-booster`,
      },
      {
        slug: "social-schedule-optimizer",
        label: "Content Schedule Optimizer",
        description: "Sugiere los mejores días y horarios orientativos para publicar en cada plataforma.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/social-media/schedule-optimizer`,
      },
      {
        slug: "social-audit",
        label: "Social Media Audit",
        description: "Genera una auditoría honesta de tu presencia en redes sociales con recomendaciones.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/social-media/audit`,
      },
    ],
  },
  {
    slug: "blog-seo-ai",
    label: "Blog & SEO AI",
    description: "Redacción de blog y optimización SEO moderna — nunca inventa métricas de posicionamiento reales.",
    icon: Newspaper,
    tools: [
      {
        slug: "seo-title",
        label: "SEO Title Generator",
        description: "Genera títulos SEO de hasta 60 caracteres con la palabra clave objetivo.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/blog-seo/title`,
      },
      {
        slug: "seo-meta-description",
        label: "Meta Description Generator",
        description: "Genera meta descripciones de 140-160 caracteres con la palabra clave objetivo.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/blog-seo/meta-description`,
      },
      {
        slug: "seo-keyword-research",
        label: "Keyword Research Assistant",
        description: "Sugiere variantes semánticas y preguntas relacionadas para un tema, sin inventar métricas reales.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/blog-seo/keyword-research`,
      },
      {
        slug: "seo-blog-outline",
        label: "Blog Outline Generator",
        description: "Genera un esquema de encabezados H1/H2/H3 para un artículo de blog.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/blog-seo/blog-outline`,
      },
      {
        slug: "seo-blog-writer",
        label: "Complete Blog Writer",
        description: "Redacta un artículo de blog completo con encabezados y la palabra clave integrada de forma natural.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/blog-seo/blog-writer`,
      },
      {
        slug: "seo-faq",
        label: "FAQ Generator",
        description: "Genera preguntas frecuentes con respuestas breves, listas para datos estructurados FAQ.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/blog-seo/faq`,
      },
      {
        slug: "seo-internal-links",
        label: "Internal Linking Suggestions",
        description: "Sugiere texto ancla y destinos de enlazado interno para un contenido.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/blog-seo/internal-links`,
      },
      {
        slug: "seo-snippet-optimizer",
        label: "Featured Snippet Optimizer",
        description: "Redacta una respuesta optimizada para ganar el featured snippet de una pregunta.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/blog-seo/snippet-optimizer`,
      },
      {
        slug: "seo-article-rewriter",
        label: "Article Rewriter",
        description: "Reescribe un artículo conservando los hechos originales, mejorando claridad y SEO on-page.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/blog-seo/rewriter`,
      },
      {
        slug: "seo-content-optimizer",
        label: "SEO Content Optimizer",
        description: "Analiza un contenido y sugiere mejoras de SEO on-page, sin inventar datos de posicionamiento real.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/blog-seo/content-optimizer`,
      },
    ],
  },
  {
    slug: "email-marketing-ai",
    label: "Email Marketing AI",
    description: "Redacción de email marketing moderno — nunca promete tasas de apertura, conversiones ni resultados reales.",
    icon: Mail,
    tools: [
      {
        slug: "email-subject-line",
        label: "Subject Line Generator",
        description: "Genera asuntos de email que generan curiosidad, sin prometer tasas de apertura.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/email-marketing/subject-line`,
      },
      {
        slug: "email-writer",
        label: "Email Writer",
        description: "Redacta un email completo con asunto, cuerpo y llamada a la acción.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/email-marketing/writer`,
      },
      {
        slug: "email-welcome",
        label: "Welcome Email Generator",
        description: "Genera un email de bienvenida para nuevos suscriptores o clientes.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/email-marketing/welcome`,
      },
      {
        slug: "email-newsletter",
        label: "Newsletter Generator",
        description: "Genera una newsletter estructurada en secciones a partir de los temas indicados.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/email-marketing/newsletter`,
      },
      {
        slug: "email-promotional",
        label: "Promotional Email Generator",
        description: "Genera un email promocional usando únicamente los datos de la oferta que proporciones.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/email-marketing/promotional`,
      },
      {
        slug: "email-followup",
        label: "Follow-Up Email Generator",
        description: "Genera un email de seguimiento respetuoso y útil.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/email-marketing/follow-up`,
      },
      {
        slug: "email-abandoned-cart",
        label: "Abandoned Cart Email",
        description: "Genera un email de recuperación de carrito abandonado.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/email-marketing/abandoned-cart`,
      },
      {
        slug: "email-cold",
        label: "Cold Email Generator",
        description: "Genera un email de primer contacto breve, personalizado y sin falsa urgencia.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/email-marketing/cold-email`,
      },
      {
        slug: "email-sequence",
        label: "Email Sequence Generator",
        description: "Diseña una secuencia de varios emails con un propósito claro por cada uno.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/email-marketing/sequence`,
      },
      {
        slug: "email-cta-optimizer",
        label: "CTA Email Optimizer",
        description: "Sugiere mejoras a la llamada a la acción de un email, sin prometer aumentos de conversión.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/email-marketing/cta-optimizer`,
      },
    ],
  },
  {
    slug: "tiktok-ai",
    label: "TikTok AI",
    description: "Vídeo corto para TikTok — nunca inventa tendencias, sonidos ni estadísticas reales vigentes.",
    icon: Flame,
    tools: [
      {
        slug: "tiktok-viral-video-ideas",
        label: "Viral Video Ideas",
        description: "Genera ideas de vídeo para TikTok organizadas por categoría, sin inventar tendencias.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/tiktok-ai/viral-ideas`,
      },
      {
        slug: "tiktok-hook-generator",
        label: "Hook Generator",
        description: "Genera hooks que enganchan en el primer segundo y medio de un vídeo de TikTok.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/tiktok-ai/hooks`,
      },
      {
        slug: "tiktok-script-generator",
        label: "TikTok Script Generator",
        description: "Genera el guion completo de un vídeo de TikTok: hook, desarrollo, CTA y texto en pantalla.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/tiktok-ai/script`,
      },
      {
        slug: "tiktok-caption-generator",
        label: "Caption Generator",
        description: "Genera captions breves y casuales para TikTok.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/tiktok-ai/caption`,
      },
      {
        slug: "tiktok-hashtag-generator",
        label: "Hashtag Generator",
        description: "Genera hashtags de nicho y descubribilidad para TikTok, sin afirmar que están en tendencia.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/tiktok-ai/hashtags`,
      },
      {
        slug: "tiktok-video-series-planner",
        label: "Video Series Planner",
        description: "Planifica una serie de vídeos de TikTok conectados entre sí.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/tiktok-ai/series-planner`,
      },
      {
        slug: "tiktok-trend-adaptation",
        label: "Trend Adaptation Assistant",
        description: "Adapta una tendencia que tú describas a tu nicho — nunca asume que una tendencia sigue vigente.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/tiktok-ai/trend-adaptation`,
      },
      {
        slug: "tiktok-cta-generator",
        label: "Call To Action Generator",
        description: "Genera llamadas a la acción breves y naturales para TikTok.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/tiktok-ai/cta`,
      },
      {
        slug: "tiktok-profile-bio",
        label: "Profile Bio Generator",
        description: "Genera biografías de TikTok dentro del límite de 80 caracteres.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/tiktok-ai/bio`,
      },
      {
        slug: "tiktok-posting-strategy",
        label: "Posting Strategy Generator",
        description: "Sugiere una estrategia de publicación orientativa para TikTok, sin datos de analítica real.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/tiktok-ai/posting-strategy`,
      },
    ],
  },
  {
    slug: "facebook-ai",
    label: "Facebook AI",
    description: "Publicaciones, anuncios y comunidad de Facebook — nunca inventa alcance, engagement ni resultados reales.",
    icon: Users2,
    tools: [
      {
        slug: "facebook-post-generator",
        label: "Facebook Post Generator",
        description: "Genera publicaciones de Facebook cercanas y conversacionales.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/facebook-ai/post`,
      },
      {
        slug: "facebook-long-form-post",
        label: "Long Form Post Generator",
        description: "Escribe una publicación larga y narrativa aprovechando el formato extendido de Facebook.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/facebook-ai/long-form-post`,
      },
      {
        slug: "facebook-story",
        label: "Story Generator",
        description: "Genera texto breve para Stories de Facebook.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/facebook-ai/story`,
      },
      {
        slug: "facebook-caption",
        label: "Caption Generator",
        description: "Genera captions de Facebook que complementan una imagen o vídeo.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/facebook-ai/caption`,
      },
      {
        slug: "facebook-comment-reply",
        label: "Comment Reply Generator",
        description: "Redacta una respuesta humana y cercana a un comentario de Facebook.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/facebook-ai/comment-reply`,
      },
      {
        slug: "facebook-ad-copy",
        label: "Facebook Ad Copy Generator",
        description: "Genera copy de anuncio de Facebook Ads honesto, sin prometer resultados.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/facebook-ai/ad-copy`,
      },
      {
        slug: "facebook-community-engagement",
        label: "Community Engagement Generator",
        description: "Genera publicaciones pensadas para fomentar conversación en Páginas y Grupos.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/facebook-ai/community-engagement`,
      },
      {
        slug: "facebook-event-promotion",
        label: "Event Promotion Generator",
        description: "Genera una publicación de promoción de evento usando solo los datos que proporciones.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/facebook-ai/event-promotion`,
      },
      {
        slug: "facebook-page-bio",
        label: "Facebook Page Bio Generator",
        description: "Genera biografías de Página de Facebook dentro del límite de 101 caracteres.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/facebook-ai/bio`,
      },
      {
        slug: "facebook-content-planner",
        label: "Facebook Content Planner",
        description: "Genera un calendario de contenido de Facebook distribuido por días.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/facebook-ai/content-planner`,
      },
    ],
  },
  {
    slug: "linkedin-ai",
    label: "LinkedIn AI",
    description: "Contenido profesional para LinkedIn — nunca inventa experiencia, logros ni promete contrataciones.",
    icon: IdCard,
    tools: [
      {
        slug: "linkedin-post",
        label: "LinkedIn Post Generator",
        description: "Genera publicaciones de LinkedIn con registro profesional y gancho inicial.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/linkedin-ai/post`,
      },
      {
        slug: "linkedin-article",
        label: "Professional Article Generator",
        description: "Redacta un artículo profesional largo para LinkedIn (formato Pulse).",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/linkedin-ai/article`,
      },
      {
        slug: "linkedin-carousel",
        label: "Carousel Content Generator",
        description: "Estructura el contenido de un carrusel (documento PDF) de LinkedIn diapositiva por diapositiva.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/linkedin-ai/carousel`,
      },
      {
        slug: "linkedin-hooks",
        label: "LinkedIn Hook Generator",
        description: "Genera las primeras líneas de una publicación para maximizar el clic en 'ver más'.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/linkedin-ai/hooks`,
      },
      {
        slug: "linkedin-headline",
        label: "Profile Headline Generator",
        description: "Genera titulares de perfil de LinkedIn dentro del límite de 220 caracteres.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/linkedin-ai/headline`,
      },
      {
        slug: "linkedin-about-section",
        label: "About Section Generator",
        description: "Redacta la sección 'Acerca de' de LinkedIn usando únicamente la información profesional que proporciones.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/linkedin-ai/about-section`,
      },
      {
        slug: "linkedin-experience-description",
        label: "Experience Description Generator",
        description: "Convierte tus responsabilidades reales en una descripción de experiencia pulida, sin inventar logros.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/linkedin-ai/experience-description`,
      },
      {
        slug: "linkedin-company-page",
        label: "Company Page Content Generator",
        description: "Genera contenido para la Página de empresa de LinkedIn con voz corporativa.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/linkedin-ai/company-page`,
      },
      {
        slug: "linkedin-networking-message",
        label: "Networking Message Generator",
        description: "Genera un mensaje de networking breve y respetuoso, sin prometer resultados.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/linkedin-ai/networking-message`,
      },
      {
        slug: "linkedin-branding-strategy",
        label: "Personal Branding Strategy Generator",
        description: "Genera una estrategia de marca personal en LinkedIn, sin prometer resultados garantizados.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/linkedin-ai/branding-strategy`,
      },
    ],
  },
  {
    slug: "image-ai",
    label: "Image AI",
    description: "Genera prompts de imagen extremadamente detallados — no genera imágenes ni integra ningún proveedor externo.",
    icon: Aperture,
    tools: [
      {
        slug: "image-prompt-generator",
        label: "Image Prompt Generator",
        description: "Genera un prompt de imagen detallado y agnóstico de motor, listo para pegar en tu generador preferido.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/image-ai/image-prompt`,
      },
      {
        slug: "photo-prompt-generator",
        label: "Photo Prompt Generator",
        description: "Genera un prompt de fotografía fotorrealista con detalles técnicos.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/image-ai/photo-prompt`,
      },
      {
        slug: "product-photography-prompt",
        label: "Product Photography Prompt",
        description: "Genera un prompt de fotografía de producto profesional, usando solo la descripción que proporciones.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/image-ai/product-photography`,
      },
      {
        slug: "logo-prompt-generator",
        label: "Logo Prompt Generator",
        description: "Genera un prompt para un logotipo limpio y memorable.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/image-ai/logo-prompt`,
      },
      {
        slug: "poster-prompt-generator",
        label: "Poster Prompt Generator",
        description: "Genera un prompt de cartel con jerarquía visual clara.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/image-ai/poster-prompt`,
      },
      {
        slug: "social-media-image-prompt",
        label: "Social Media Image Prompt",
        description: "Genera un prompt de imagen pensado para una plataforma social concreta.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/image-ai/social-image-prompt`,
      },
      {
        slug: "thumbnail-prompt-generator",
        label: "Thumbnail Prompt Generator",
        description: "Genera un prompt de miniatura de vídeo con alto contraste y lectura rápida.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/image-ai/thumbnail-prompt`,
      },
      {
        slug: "character-prompt-generator",
        label: "Character Prompt Generator",
        description: "Genera un prompt de personaje usando únicamente la descripción que proporciones.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/image-ai/character-prompt`,
      },
      {
        slug: "background-prompt-generator",
        label: "Background Prompt Generator",
        description: "Genera un prompt de fondo o escenario con profundidad visual.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/image-ai/background-prompt`,
      },
      {
        slug: "style-transfer-prompt",
        label: "Style Transfer Prompt Generator",
        description: "Combina un contenido base con un estilo artístico objetivo en un único prompt.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/image-ai/style-transfer`,
      },
    ],
  },
  {
    slug: "document-ai",
    label: "Document AI",
    description: "Procesa documentos de texto — resume, traduce, corrige y reescribe usando únicamente el texto que proporciones.",
    icon: ScrollText,
    tools: [
      {
        slug: "document-summarizer",
        label: "Document Summarizer",
        description: "Resume un documento largo conservando fielmente sus ideas y datos.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/document-ai/summarizer`,
      },
      {
        slug: "document-translator",
        label: "Document Translator",
        description: "Traduce un documento de forma fiel, sin alterar cifras, nombres ni fechas.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/document-ai/translator`,
      },
      {
        slug: "grammar-style-checker",
        label: "Grammar & Style Checker",
        description: "Corrige ortografía, gramática y estilo sin cambiar el significado del documento.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/document-ai/grammar-style`,
      },
      {
        slug: "document-rewriter",
        label: "Document Rewriter",
        description: "Reescribe un documento con un tono distinto, conservando el significado y los datos originales.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/document-ai/rewriter`,
      },
      {
        slug: "contract-simplifier",
        label: "Contract Simplifier",
        description: "Reescribe un contrato o documento legal en lenguaje sencillo, sin alterar sus condiciones.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/document-ai/contract-simplifier`,
      },
      {
        slug: "meeting-notes-generator",
        label: "Meeting Notes Generator",
        description: "Organiza notas o una transcripción de reunión en un acta clara con decisiones y próximos pasos.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/document-ai/meeting-notes`,
      },
      {
        slug: "executive-summary-generator",
        label: "Executive Summary Generator",
        description: "Condensa un documento en un resumen ejecutivo orientado a la audiencia indicada.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/document-ai/executive-summary`,
      },
      {
        slug: "bullet-point-generator",
        label: "Bullet Point Generator",
        description: "Convierte un documento en una lista de puntos clave clara y escaneable.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/document-ai/bullet-points`,
      },
      {
        slug: "formal-document-generator",
        label: "Formal Document Generator",
        description: "Redacta un documento formal (carta, memorándum, comunicado) a partir del propósito que indiques.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/document-ai/formal-document`,
      },
      {
        slug: "document-analyzer",
        label: "Document Analyzer",
        description: "Analiza estructura, claridad y coherencia de un documento usando solo evidencia del propio texto.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/document-ai/analyzer`,
      },
    ],
  },
  {
    slug: "video-ai",
    label: "Video AI",
    description: "Genera prompts, guiones y planes de producción de video — no genera vídeo ni integra ningún proveedor externo.",
    icon: Film,
    tools: [
      {
        slug: "video-prompt-generator",
        label: "Video Prompt Generator",
        description: "Genera un prompt de video detallado y agnóstico de motor, listo para pegar en tu generador preferido.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/video-ai/video-prompt`,
      },
      {
        slug: "ai-video-script-generator",
        label: "AI Video Script Generator",
        description: "Genera el guion completo de un video: introducción, desarrollo y cierre, ajustado a la duración objetivo.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/video-ai/script`,
      },
      {
        slug: "storyboard-generator",
        label: "Storyboard Generator",
        description: "Describe un storyboard en texto, viñeta por viñeta, a partir de un guion o escena.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/video-ai/storyboard`,
      },
      {
        slug: "scene-planner",
        label: "Scene Planner",
        description: "Organiza los elementos clave de una escena a definir antes de rodar o generar, sin inventar ubicación ni personajes.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/video-ai/scene-planner`,
      },
      {
        slug: "shot-list-generator",
        label: "Shot List Generator",
        description: "Genera una lista de planos numerada (tipo, ángulo y acción) para una escena.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/video-ai/shot-list`,
      },
      {
        slug: "camera-movement-generator",
        label: "Camera Movement Generator",
        description: "Sugiere movimientos de cámara concretos que refuercen la sensación que quieres transmitir.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/video-ai/camera-movement`,
      },
      {
        slug: "cinematic-prompt-generator",
        label: "Cinematic Prompt Generator",
        description: "Genera un prompt con dirección cinematográfica clara: paleta, luz, lente y estilo.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/video-ai/cinematic-prompt`,
      },
      {
        slug: "short-video-generator",
        label: "Short Video Generator",
        description: "Genera el guion breve y el prompt visual de un video corto — no genera ningún archivo de vídeo.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/video-ai/short-video`,
      },
      {
        slug: "youtube-video-outline-generator",
        label: "YouTube Video Outline Generator",
        description: "Genera el esquema por secciones de un video de YouTube, con marcas de tiempo orientativas.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/video-ai/youtube-outline`,
      },
      {
        slug: "video-production-planner",
        label: "Video Production Planner",
        description: "Genera un plan de producción por fases (preproducción, rodaje/generación, postproducción) para un proyecto de video.",
        status: "available",
        href: (projectId) => `/dashboard/${projectId}/ai-center/video-ai/production-planner`,
      },
    ],
  },
];

export function getAllAiTools(): (AiToolCategory["tools"][number] & { categorySlug: string; categoryLabel: string })[] {
  return AI_CENTER_CATEGORIES.flatMap((category) =>
    category.tools.map((tool) => ({ ...tool, categorySlug: category.slug, categoryLabel: category.label }))
  );
}

export function getAiCategory(categorySlug: string): AiToolCategory | undefined {
  return AI_CENTER_CATEGORIES.find((category) => category.slug === categorySlug);
}

export function findAiTool(toolSlug: string): ReturnType<typeof getAllAiTools>[number] | undefined {
  return getAllAiTools().find((tool) => tool.slug === toolSlug);
}
