import type { PerformanceMetricCategory, PerformanceMetricUnit, PerformanceMetricDirection, PerformanceMetricAggregation, PerformanceResourceType } from "@/lib/performance/types";

/**
 * The central, typed metric catalog (spec section 8) — the SINGLE place
 * every built-in metric key, its unit/direction/aggregation, and which
 * resources/platforms it's compatible with live. Nothing else in this
 * codebase invents a metric key; every record/definition/comparison editor
 * resolves a key through `findMetricDefinition` below. Project-scoped custom
 * keys are validated and persisted separately (PerformanceMetricDefinition,
 * see src/server/services/performance-metric-definitions.ts) — never an
 * arbitrary string accepted here.
 */

export interface MetricFormulaSpec {
  numeratorKey: string;
  denominatorKey: string;
  description: string;
}

export interface MetricDefinitionSpec {
  key: string;
  name: string;
  description: string;
  category: PerformanceMetricCategory;
  unit: PerformanceMetricUnit;
  direction: PerformanceMetricDirection;
  aggregation: PerformanceMetricAggregation;
  compatibleResourceTypes: PerformanceResourceType[];
  /** Empty = compatible with any platform. */
  compatiblePlatforms: string[];
  supportsCumulative: boolean;
  supportsAverage: boolean;
  supportsPercentage: boolean;
  supportsComparison: boolean;
  requiresNumeratorDenominator: boolean;
  expectedMin?: number;
  expectedMax?: number;
  /** True for metrics that can only ever arrive via MANUAL/CSV_IMPORT/JSON_IMPORT/EXTERNAL_PROVIDER — never computed internally. */
  isExternal: boolean;
  /** True for metrics with a declared internal formula (spec section 9) — see src/lib/performance/derived-metrics.ts. */
  isDerived: boolean;
  formula?: MetricFormulaSpec;
}

const ALL_RESOURCES: PerformanceResourceType[] = ["CONTENT_ITEM", "CONTENT_VERSION", "CAMPAIGN", "CAMPAIGN_CONTENT_PIECE", "SOCIAL_POST", "EXPERIMENT_VARIANT", "PLATFORM", "PROJECT"];

export const PERFORMANCE_METRIC_DEFINITIONS: MetricDefinitionSpec[] = [
  // --- CONTENT ---------------------------------------------------------
  { key: "content_items_created", name: "ContentItem creados", description: "Cantidad de piezas de contenido creadas.", category: "CONTENT", unit: "COUNT", direction: "NEUTRAL", aggregation: "SUM", compatibleResourceTypes: ["CONTENT_ITEM", "PROJECT"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "content_versions_created", name: "Revisiones de contenido", description: "Número de ContentVersion creadas (revisiones) para una pieza.", category: "CONTENT", unit: "COUNT", direction: "NEUTRAL", aggregation: "SUM", compatibleResourceTypes: ["CONTENT_ITEM"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "content_approval_time_seconds", name: "Tiempo hasta aprobación", description: "Segundos desde la creación hasta la aprobación (medido vía la publicación asociada cuando existe approvedAt real).", category: "CONTENT", unit: "SECONDS", direction: "LOWER_IS_BETTER", aggregation: "AVERAGE", compatibleResourceTypes: ["CONTENT_ITEM", "SOCIAL_POST"], compatiblePlatforms: [], supportsCumulative: false, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "content_publish_time_seconds", name: "Tiempo hasta publicación interna", description: "Segundos desde la creación hasta la publicación interna.", category: "CONTENT", unit: "SECONDS", direction: "LOWER_IS_BETTER", aggregation: "AVERAGE", compatibleResourceTypes: ["CONTENT_ITEM", "SOCIAL_POST"], compatiblePlatforms: [], supportsCumulative: false, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "content_seo_score", name: "Puntuación SEO", description: "Puntuación determinista del analizador SEO existente (0-100).", category: "CONTENT", unit: "SCORE", direction: "HIGHER_IS_BETTER", aggregation: "LAST", compatibleResourceTypes: ["CONTENT_ITEM"], compatiblePlatforms: [], supportsCumulative: false, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, expectedMin: 0, expectedMax: 100, isExternal: false, isDerived: false },
  { key: "content_knowledge_citations_count", name: "Citas de Knowledge Base", description: "Número de citas de Knowledge Base insertadas en el contenido.", category: "CONTENT", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["CONTENT_ITEM"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "content_length_chars", name: "Longitud del contenido", description: "Longitud del cuerpo del contenido en caracteres.", category: "CONTENT", unit: "COUNT", direction: "NEUTRAL", aggregation: "LAST", compatibleResourceTypes: ["CONTENT_ITEM", "CONTENT_VERSION"], compatiblePlatforms: [], supportsCumulative: false, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },

  // --- CAMPAIGN ----------------------------------------------------------
  { key: "campaigns_created", name: "Campañas creadas", description: "Cantidad de campañas creadas en el periodo.", category: "CAMPAIGN", unit: "COUNT", direction: "NEUTRAL", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "campaign_pieces_planned", name: "Piezas planeadas", description: "Piezas de campaña planeadas (CampaignContentPiece).", category: "CAMPAIGN", unit: "COUNT", direction: "NEUTRAL", aggregation: "SUM", compatibleResourceTypes: ["CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "campaign_pieces_completed", name: "Piezas completadas", description: "Piezas de campaña en estado completado/publicado.", category: "CAMPAIGN", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "campaign_progress_percent", name: "Progreso de campaña", description: "Porcentaje de piezas completadas sobre planeadas.", category: "CAMPAIGN", unit: "PERCENTAGE", direction: "HIGHER_IS_BETTER", aggregation: "LAST", compatibleResourceTypes: ["CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: false, supportsAverage: true, supportsPercentage: true, supportsComparison: true, requiresNumeratorDenominator: true, expectedMin: 0, expectedMax: 100, isExternal: false, isDerived: true, formula: { numeratorKey: "campaign_pieces_completed", denominatorKey: "campaign_pieces_planned", description: "piezas completadas / piezas planeadas" } },
  { key: "campaign_delayed_pieces_count", name: "Piezas retrasadas", description: "Piezas con fecha programada ya vencida sin completar.", category: "CAMPAIGN", unit: "COUNT", direction: "LOWER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "campaign_related_posts_count", name: "Publicaciones relacionadas", description: "SocialPost vinculados a la campaña.", category: "CAMPAIGN", unit: "COUNT", direction: "NEUTRAL", aggregation: "SUM", compatibleResourceTypes: ["CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "campaign_marketing_brain_runs_count", name: "Ejecuciones de Marketing Brain", description: "Ejecuciones de Marketing Brain asociadas a la campaña.", category: "CAMPAIGN", unit: "COUNT", direction: "NEUTRAL", aggregation: "SUM", compatibleResourceTypes: ["CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "campaign_marketing_brain_failed_runs_count", name: "Ejecuciones de Marketing Brain fallidas", description: "Ejecuciones de Marketing Brain fallidas o parciales.", category: "CAMPAIGN", unit: "COUNT", direction: "LOWER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },

  // --- SOCIAL / PUBLICACIONES --------------------------------------------
  { key: "social_posts_created", name: "Publicaciones creadas", description: "SocialPost creados.", category: "SOCIAL", unit: "COUNT", direction: "NEUTRAL", aggregation: "SUM", compatibleResourceTypes: ["PROJECT", "CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "social_posts_approved", name: "Publicaciones aprobadas", description: "SocialPost aprobados.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT", "CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "social_posts_rejected", name: "Publicaciones rechazadas", description: "Eventos de rechazo registrados sobre publicaciones.", category: "SOCIAL", unit: "COUNT", direction: "LOWER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT", "CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "social_posts_failed", name: "Publicaciones con fallo interno", description: "SocialPost en estado FAILED (fallo interno, nunca un fallo de plataforma externa real).", category: "SOCIAL", unit: "COUNT", direction: "LOWER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT", "CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "social_post_approval_time_seconds", name: "Tiempo en aprobación", description: "Segundos entre creación y approvedAt.", category: "SOCIAL", unit: "SECONDS", direction: "LOWER_IS_BETTER", aggregation: "AVERAGE", compatibleResourceTypes: ["SOCIAL_POST"], compatiblePlatforms: [], supportsCumulative: false, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "social_posts_missing_media_count", name: "Publicaciones sin medio", description: "SocialPost sin ningún FileAsset adjunto.", category: "SOCIAL", unit: "COUNT", direction: "LOWER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT", "CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "approval_rate", name: "Tasa de aprobación", description: "Proporción de decisiones que resultan en aprobación.", category: "SOCIAL", unit: "PERCENTAGE", direction: "HIGHER_IS_BETTER", aggregation: "RATE", compatibleResourceTypes: ["PROJECT", "CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: false, supportsAverage: true, supportsPercentage: true, supportsComparison: true, requiresNumeratorDenominator: true, expectedMin: 0, expectedMax: 100, isExternal: false, isDerived: true, formula: { numeratorKey: "social_posts_approved", denominatorKey: "social_posts_decided_total", description: "aprobaciones / decisiones totales (aprobadas + rechazadas)" } },

  // --- AUTOMATION / IA -----------------------------------------------------
  { key: "agent_runs_completed", name: "AgentRun completados", description: "Ejecuciones de AI Agent Studio completadas con éxito.", category: "AUTOMATION", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "agent_runs_failed", name: "AgentRun fallidos", description: "Ejecuciones de AI Agent Studio fallidas.", category: "AUTOMATION", unit: "COUNT", direction: "LOWER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "workflow_runs_completed", name: "WorkflowRun completados", description: "Ejecuciones de AI Workflows completadas.", category: "AUTOMATION", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "workflow_automation_runs_completed", name: "WorkflowAutomationRun completados", description: "Ejecuciones de Automation Center completadas.", category: "AUTOMATION", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "automation_runs_terminal_total", name: "Ejecuciones de automatización terminadas", description: "Ejecuciones de Automation Center en cualquier estado terminal (denominador de automation_success_rate).", category: "AUTOMATION", unit: "COUNT", direction: "NEUTRAL", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: false, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "automation_success_rate", name: "Tasa de éxito de automatización", description: "Proporción de ejecuciones de Automation Center que terminan en éxito.", category: "AUTOMATION", unit: "PERCENTAGE", direction: "HIGHER_IS_BETTER", aggregation: "RATE", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: [], supportsCumulative: false, supportsAverage: true, supportsPercentage: true, supportsComparison: true, requiresNumeratorDenominator: true, expectedMin: 0, expectedMax: 100, isExternal: false, isDerived: true, formula: { numeratorKey: "workflow_automation_runs_completed", denominatorKey: "automation_runs_terminal_total", description: "ejecuciones completadas con éxito / ejecuciones terminadas" } },

  // --- KNOWLEDGE ----------------------------------------------------------
  { key: "knowledge_sources_ready", name: "Fuentes listas", description: "Fuentes de Knowledge Base en estado READY/PARTIALLY_READY.", category: "KNOWLEDGE", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "knowledge_sources_failed", name: "Fuentes con error", description: "Fuentes de Knowledge Base en estado FAILED o NEEDS_OCR.", category: "KNOWLEDGE", unit: "COUNT", direction: "LOWER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "knowledge_queries_count", name: "Consultas realizadas", description: "Consultas de Knowledge Base realizadas.", category: "KNOWLEDGE", unit: "COUNT", direction: "NEUTRAL", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "knowledge_queries_without_evidence_count", name: "Consultas sin evidencia", description: "Consultas cuya respuesta no citó ninguna fuente.", category: "KNOWLEDGE", unit: "COUNT", direction: "LOWER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
  { key: "knowledge_citations_used_count", name: "Citas usadas", description: "Citas de Knowledge Base efectivamente usadas en respuestas o contenido.", category: "KNOWLEDGE", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },

  // --- EXTERNAL (spec section 7) — never computed internally, only manual/imported/synced ---
  { key: "impressions", name: "Impresiones", description: "Veces que el contenido fue mostrado.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "reach", name: "Alcance", description: "Cuentas únicas alcanzadas.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "views", name: "Reproducciones", description: "Reproducciones o vistas totales.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "clicks", name: "Clics", description: "Clics totales.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "reactions", name: "Reacciones", description: "Reacciones totales.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "likes", name: "Me gusta", description: "Me gusta totales.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "comments", name: "Comentarios", description: "Comentarios totales.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "shares", name: "Compartidos", description: "Veces compartido.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "saves", name: "Guardados", description: "Veces guardado.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "followers_gained", name: "Seguidores ganados", description: "Nuevos seguidores atribuidos.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "profile_visits", name: "Visitas al perfil", description: "Visitas al perfil atribuidas.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "link_clicks", name: "Clics en enlace", description: "Clics en el enlace del post.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "watch_time_seconds", name: "Tiempo de reproducción total", description: "Segundos totales de reproducción.", category: "SOCIAL", unit: "SECONDS", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "average_watch_time_seconds", name: "Tiempo de reproducción promedio", description: "Segundos promedio de reproducción.", category: "SOCIAL", unit: "SECONDS", direction: "HIGHER_IS_BETTER", aggregation: "AVERAGE", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: false, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "video_completion_rate", name: "Tasa de finalización de video", description: "Proporción de reproducciones completas.", category: "SOCIAL", unit: "PERCENTAGE", direction: "HIGHER_IS_BETTER", aggregation: "RATE", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: false, supportsAverage: true, supportsPercentage: true, supportsComparison: true, requiresNumeratorDenominator: true, expectedMin: 0, expectedMax: 100, isExternal: true, isDerived: false },
  { key: "engagement_rate", name: "Tasa de interacción", description: "Interacciones sobre alcance o impresiones.", category: "SOCIAL", unit: "PERCENTAGE", direction: "HIGHER_IS_BETTER", aggregation: "RATE", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: false, supportsAverage: true, supportsPercentage: true, supportsComparison: true, requiresNumeratorDenominator: true, expectedMin: 0, expectedMax: 100, isExternal: true, isDerived: true, formula: { numeratorKey: "engagement_total", denominatorKey: "reach", description: "interacciones (likes+comments+shares+saves) / alcance o impresiones" } },
  { key: "click_through_rate", name: "Tasa de clics (CTR)", description: "Clics sobre impresiones.", category: "SOCIAL", unit: "PERCENTAGE", direction: "HIGHER_IS_BETTER", aggregation: "RATE", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: false, supportsAverage: true, supportsPercentage: true, supportsComparison: true, requiresNumeratorDenominator: true, expectedMin: 0, expectedMax: 100, isExternal: true, isDerived: true, formula: { numeratorKey: "clicks", denominatorKey: "impressions", description: "clics / impresiones" } },
  { key: "conversion_count", name: "Conversiones", description: "Conversiones atribuidas.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "conversion_rate", name: "Tasa de conversión", description: "Conversiones sobre clics.", category: "SOCIAL", unit: "PERCENTAGE", direction: "HIGHER_IS_BETTER", aggregation: "RATE", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: false, supportsAverage: true, supportsPercentage: true, supportsComparison: true, requiresNumeratorDenominator: true, expectedMin: 0, expectedMax: 100, isExternal: true, isDerived: true, formula: { numeratorKey: "conversion_count", denominatorKey: "clicks", description: "conversiones / clics" } },
  { key: "revenue_value", name: "Ingreso (dato analítico)", description: "Valor monetario importado por el usuario — únicamente analítico, nunca facturación real.", category: "SOCIAL", unit: "CURRENCY", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "cost_value", name: "Costo (dato analítico)", description: "Valor monetario importado por el usuario — únicamente analítico, nunca facturación real.", category: "SOCIAL", unit: "CURRENCY", direction: "LOWER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },

  // --- GOOGLE ANALYTICS 4 (Fase 39) — real values from the GA4 Data API's runReport, never computed
  // internally. Metric API names verified against the CURRENT GA4 Data API v1beta metric catalog at
  // implementation time: activeUsers, newUsers, sessions, screenPageViews, engagementRate,
  // averageSessionDuration, eventCount, keyEvents, totalRevenue (src/lib/integrations/google-ga4-client.ts
  // maps each catalog key to its exact API metric name — never guessed at call time). `keyEvents`
  // replaced the older `conversions` metric name after Google's 2024 "conversions → key events"
  // rename; this catalog intentionally uses the current name only. GA4's `engagementRate` is returned
  // as a 0-1 fraction by the API — persisted here multiplied by 100 to match this catalog's existing
  // PERCENTAGE convention (0-100, see click_through_rate above), never mixed as a raw decimal.
  { key: "ga4.active_users", name: "Usuarios activos (GA4)", description: "Usuarios activos en el periodo, según Google Analytics 4.", category: "ANALYTICS", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: ["ga4"], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "ga4.new_users", name: "Usuarios nuevos (GA4)", description: "Usuarios que interactuaron por primera vez, según Google Analytics 4.", category: "ANALYTICS", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: ["ga4"], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "ga4.sessions", name: "Sesiones (GA4)", description: "Sesiones registradas, según Google Analytics 4.", category: "ANALYTICS", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: ["ga4"], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "ga4.page_views", name: "Vistas de página (GA4)", description: "screenPageViews — vistas de página/pantalla, según Google Analytics 4.", category: "ANALYTICS", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: ["ga4"], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "ga4.engagement_rate", name: "Tasa de interacción (GA4)", description: "engagementRate de Google Analytics 4 — ya calculada por Google, persistida en escala 0-100.", category: "ANALYTICS", unit: "PERCENTAGE", direction: "HIGHER_IS_BETTER", aggregation: "AVERAGE", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: ["ga4"], supportsCumulative: false, supportsAverage: true, supportsPercentage: true, supportsComparison: true, requiresNumeratorDenominator: false, expectedMin: 0, expectedMax: 100, isExternal: true, isDerived: false },
  { key: "ga4.average_session_duration", name: "Duración media de sesión (GA4)", description: "averageSessionDuration en segundos, según Google Analytics 4.", category: "ANALYTICS", unit: "SECONDS", direction: "HIGHER_IS_BETTER", aggregation: "AVERAGE", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: ["ga4"], supportsCumulative: false, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "ga4.event_count", name: "Eventos (GA4)", description: "eventCount — eventos totales, según Google Analytics 4.", category: "ANALYTICS", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: ["ga4"], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "ga4.key_events", name: "Eventos clave (GA4)", description: "keyEvents — eventos marcados como clave/conversión en Google Analytics 4 (nombre vigente tras el cambio de 'conversiones' a 'eventos clave').", category: "ANALYTICS", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: ["ga4"], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "ga4.total_revenue", name: "Ingresos totales (GA4)", description: "totalRevenue, según Google Analytics 4 — se conserva la moneda devuelta por la fuente, sin conversión.", category: "ANALYTICS", unit: "CURRENCY", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: ["ga4"], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },

  // --- GOOGLE SEARCH CONSOLE (Fase 39) — real values from the Search Console API's searchanalytics.query,
  // never computed internally. `ctr` is returned as a 0-1 fraction by the API — persisted multiplied by
  // 100 for the same PERCENTAGE convention reason as ga4.engagement_rate above.
  { key: "gsc.clicks", name: "Clics (Search Console)", description: "Clics totales en resultados de búsqueda orgánica, según Google Search Console.", category: "ANALYTICS", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: ["gsc"], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "gsc.impressions", name: "Impresiones (Search Console)", description: "Impresiones totales en resultados de búsqueda orgánica, según Google Search Console.", category: "ANALYTICS", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: ["gsc"], supportsCumulative: true, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "gsc.ctr", name: "CTR (Search Console)", description: "Tasa de clics ya calculada por Google Search Console, persistida en escala 0-100.", category: "ANALYTICS", unit: "PERCENTAGE", direction: "HIGHER_IS_BETTER", aggregation: "AVERAGE", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: ["gsc"], supportsCumulative: false, supportsAverage: true, supportsPercentage: true, supportsComparison: true, requiresNumeratorDenominator: false, expectedMin: 0, expectedMax: 100, isExternal: true, isDerived: false },
  { key: "gsc.average_position", name: "Posición media (Search Console)", description: "Posición media en resultados de búsqueda orgánica — un valor MÁS BAJO es mejor.", category: "ANALYTICS", unit: "SCORE", direction: "LOWER_IS_BETTER", aggregation: "AVERAGE", compatibleResourceTypes: ["PROJECT"], compatiblePlatforms: ["gsc"], supportsCumulative: false, supportsAverage: true, supportsPercentage: false, supportsComparison: true, requiresNumeratorDenominator: false, expectedMin: 1, isExternal: true, isDerived: false },

  // --- Internal composite helpers used only as formula components (never shown standalone in pickers, but valid metricKeys) ---
  { key: "engagement_total", name: "Interacciones totales", description: "Suma de likes+comments+shares+saves — componente interno de engagement_rate.", category: "SOCIAL", unit: "COUNT", direction: "HIGHER_IS_BETTER", aggregation: "SUM", compatibleResourceTypes: ALL_RESOURCES, compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: false, requiresNumeratorDenominator: false, isExternal: true, isDerived: false },
  { key: "social_posts_decided_total", name: "Decisiones de aprobación totales", description: "Aprobadas + rechazadas — denominador de approval_rate.", category: "SOCIAL", unit: "COUNT", direction: "NEUTRAL", aggregation: "SUM", compatibleResourceTypes: ["PROJECT", "CAMPAIGN"], compatiblePlatforms: [], supportsCumulative: true, supportsAverage: false, supportsPercentage: false, supportsComparison: false, requiresNumeratorDenominator: false, isExternal: false, isDerived: false },
];

export function findMetricDefinition(key: string): MetricDefinitionSpec | undefined {
  return PERFORMANCE_METRIC_DEFINITIONS.find((d) => d.key === key);
}

export function listMetricDefinitions(): MetricDefinitionSpec[] {
  return PERFORMANCE_METRIC_DEFINITIONS;
}

export function listMetricDefinitionsByCategory(category: PerformanceMetricCategory): MetricDefinitionSpec[] {
  return PERFORMANCE_METRIC_DEFINITIONS.filter((d) => d.category === category);
}

/** A key is either a real built-in catalog key, or a project-scoped "custom." key validated separately (spec section 8: "no permitas claves arbitrarias salvo mediante custom_metric validada"). */
export function isCustomMetricKey(key: string): boolean {
  return key.startsWith("custom.");
}

export function isKnownBuiltinMetricKey(key: string): boolean {
  return Boolean(findMetricDefinition(key));
}
