/**
 * Shared, framework-free types for the AI Marketing Brain orchestrator.
 * Mirrors the enum value lists from prisma/schema.prisma exactly (kept as
 * plain string unions here so pure lib functions never need to import the
 * generated Prisma client) — see src/lib/marketing-brain/plan.ts for the
 * single source of truth on stage order/labels/dependencies.
 */

export const MARKETING_BRAIN_STEP_KEYS = [
  "INTERPRET_BRIEFING",
  "PREPARE_CAMPAIGN",
  "GENERATE_STRATEGY",
  "CREATE_PILLARS",
  "CREATE_CONTENT_PLAN",
  "CREATE_PIECES",
  "GENERATE_DRAFTS",
  "ADAPT_PLATFORMS",
  "CREATE_PUBLICATIONS",
  "PREPARE_APPROVAL",
  "PREPARE_CALENDAR",
  "SCHEDULE",
] as const;
export type MarketingBrainStepKeyValue = (typeof MARKETING_BRAIN_STEP_KEYS)[number];

/** Stage boundaries that MAY be gated behind human approval, per spec section 18 — a subset of the 12 stages (the other 5 are always automatic/informational). */
export const MARKETING_BRAIN_APPROVAL_GATE_KEYS: MarketingBrainStepKeyValue[] = [
  "PREPARE_CAMPAIGN",
  "CREATE_PILLARS",
  "CREATE_CONTENT_PLAN",
  "CREATE_PIECES",
  "GENERATE_DRAFTS",
  "CREATE_PUBLICATIONS",
  "SCHEDULE",
];

export const MARKETING_BRAIN_RUN_STATUSES = [
  "DRAFT",
  "READY",
  "RUNNING",
  "WAITING_FOR_APPROVAL",
  "PARTIALLY_COMPLETED",
  "COMPLETED",
  "FAILED",
  "CANCELLED",
  "ARCHIVED",
] as const;
export type MarketingBrainRunStatusValue = (typeof MARKETING_BRAIN_RUN_STATUSES)[number];

export const MARKETING_BRAIN_STEP_STATUSES = [
  "PENDING",
  "RUNNING",
  "COMPLETED",
  "FAILED",
  "SKIPPED",
  "CANCELLED",
  "WAITING_FOR_APPROVAL",
] as const;
export type MarketingBrainStepStatusValue = (typeof MARKETING_BRAIN_STEP_STATUSES)[number];

export type MarketingBrainErrorCategoryValue =
  | "VALIDATION"
  | "PERMISSION"
  | "DEPENDENCY"
  | "AI"
  | "DATABASE"
  | "CONFLICT"
  | "CANCELLATION"
  | "INTERNAL";

export interface StagesConfig {
  /** Which of the 12 stages this run will execute — a disabled stage is SKIPPED, never silently dropped. */
  enabled: Record<MarketingBrainStepKeyValue, boolean>;
  /** Subset of MARKETING_BRAIN_APPROVAL_GATE_KEYS this run requires a human decision for before executing. */
  approvalGates: MarketingBrainStepKeyValue[];
}

/** Every field optional — both quick and advanced briefings autosave a partial patch, same convention as every other wizard in this codebase. `mode` tracks which tab the user is on, purely for UI restoration. */
export interface MarketingBrainBriefing {
  mode?: "quick" | "advanced" | "performance";

  /** Selection for the optional Performance Center context (Fase 35 spec section 5) — stored on the SAME briefing so it autosaves like everything else; a real optimization session is only created when the user explicitly clicks "Analizar rendimiento". */
  performanceContext?: import("@/lib/marketing-brain/performance-context-types").PerformanceContextSelectionInput;

  // --- Quick briefing ---
  description?: string;
  productOrService?: string;
  objective?: string;
  startDate?: string;
  endDate?: string;
  platforms?: string[];
  brandProfileId?: string | null;
  language?: string;
  timezone?: string;
  campaignMode?: "new" | "existing" | "duplicate";
  existingCampaignId?: string | null;

  // --- Advanced briefing ---
  audience?: string;
  audienceLocation?: string;
  audienceAgeRange?: string;
  audienceInterests?: string[];
  audiencePainPoints?: string[];
  audienceNeeds?: string[];
  audienceObjections?: string[];
  audienceAwareness?: string;
  valueProposition?: string;
  offer?: string;
  primaryCTA?: string;
  tone?: string;
  forbiddenWords?: string[];
  competitors?: string[];
  budget?: number | null;
  frequencyPerWeek?: number | null;
  preferredDays?: string[];
  preferredHours?: string[];
  desiredFormats?: string[];
  targetMetrics?: string[];
  maxPieces?: number | null;
  assigneeId?: string | null;
  approverId?: string | null;
  requireApproval?: boolean;
  autoGenerateDrafts?: boolean;
  autoAdaptPlatforms?: boolean;
  autoCreatePublications?: boolean;
  schedulingMode?: "manual" | "automatic";
}

/** Deterministic normalization output — every inferred/defaulted field is listed in `inferredFields` so the UI can show it as an editable suggestion, per spec section 4. Never written to Prisma directly; downstream stages read this. */
export interface NormalizedBriefing {
  productOrService: string;
  objective: string;
  description: string;
  startDate: string;
  endDate: string;
  timezone: string;
  platforms: string[];
  brandProfileId: string | null;
  language: string;
  campaignMode: "new" | "existing" | "duplicate";
  existingCampaignId: string | null;

  audience: string;
  audienceLocation: string;
  audienceAgeRange: string;
  audienceInterests: string[];
  audiencePainPoints: string[];
  audienceNeeds: string[];
  audienceObjections: string[];
  audienceAwareness: string;
  valueProposition: string;
  offer: string;
  primaryCTA: string;
  tone: string;
  forbiddenWords: string[];
  competitors: string[];
  budget: number | null;
  targetMetrics: string[];
  frequencyPerWeek: number;
  preferredDays: string[];
  preferredHours: string[];
  desiredFormats: string[];
  maxPieces: number;
  assigneeId: string | null;
  approverId: string | null;
  requireApproval: boolean;
  autoGenerateDrafts: boolean;
  autoAdaptPlatforms: boolean;
  autoCreatePublications: boolean;
  schedulingMode: "manual" | "automatic";

  /** Field names defaulted by the deterministic layer rather than explicitly supplied by the user — must be shown as editable suggestions, never silently committed (spec section 4). */
  inferredFields: string[];
  /** Blocking validation problems (e.g. end before start) — a run cannot move past DRAFT while any are present. */
  errors: string[];
  /** Non-blocking notices (e.g. short range, platform without a real format) — shown in the confirmation screen, never prevent execution by themselves. */
  warnings: string[];
}
